Import ('s3env')

senv = s3env.Clone ()

CppTestProject(
    senv, 's3-util-test', s3env['S3VERSION'],
    source_files = senv.Glob ('*Test.cpp'),
    include_dir = senv.SrcDir('#src'),
    dependencies = ['s3-util.cpplib']
)

senv.SubBuild ()
