Import ('mainenv')

modules = ['71_vinci_bike_rental', '57_accounting', '30_server', '32_admin', '11_interfaces', '12_security', '13_dblog', '04_time', '02_db', '01_util', '00_tcp'];


syntheseenv = mainenv.SyntheseEnv (modules)

syntheseenv.SyntheseBuild (syntheseenv.DefaultModuleName ())


