
//////////////////////////////////////////////////////////////////////////////////////////
///	PDFTextService class header.
///	@file PDFTextService.hpp
///	@author hromain
///	@date 2013
///
///	This file belongs to the SYNTHESE project (public transportation specialized software)
///	Copyright (C) 2002 Hugues Romain - RCSmobility <contact@rcsmobility.com>
///
///	This program is free software; you can redistribute it and/or
///	modify it under the terms of the GNU General Public License
///	as published by the Free Software Foundation; either version 2
///	of the License, or (at your option) any later version.
///
///	This program is distributed in the hope that it will be useful,
///	but WITHOUT ANY WARRANTY; without even the implied warranty of
///	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
///	GNU General Public License for more details.
///
///	You should have received a copy of the GNU General Public License
///	along with this program; if not, write to the Free Software
///	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

#ifndef SYNTHESE_PDFTextService_H__
#define SYNTHESE_PDFTextService_H__

#include "FactorableTemplate.h"
#include "Function.h"

#include "RGBColor.h"

namespace synthese
{
	namespace pdf_cms
	{
		//////////////////////////////////////////////////////////////////////////
		///	40.15 Function : PDFTextService.
		/// See https://extranet.rcsmobility.com/projects/synthese/wiki/PDF_text
		//////////////////////////////////////////////////////////////////////////
		///	@ingroup m40Functions refFunctions
		///	@author hromain
		///	@date 2013
		/// @since 3.9.0
		class PDFTextService:
			public util::FactorableTemplate<server::Function,PDFTextService>
		{
		public:
			static const std::string PARAMETER_T;
			static const std::string PARAMETER_X;
			static const std::string PARAMETER_Y;
			static const std::string PARAMETER_FONT;
			static const std::string PARAMETER_SIZE;
			static const std::string PARAMETER_COLOR;
			static const std::string PARAMETER_ANGLE;



		protected:
			//! \name Page parameters
			//@{
				std::string _text;
				float _x;
				float _y;
				boost::optional<std::string> _font;
				boost::optional<float> _size;
				boost::optional<util::RGBColor> _color;
				float _angle;
			//@}
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Conversion from attributes to generic parameter maps.
			/// See https://extranet.rcsmobility.com/projects/synthese/wiki/PDF_text#Request
			//////////////////////////////////////////////////////////////////////////
			///	@return Generated parameters map
			/// @author hromain
			/// @date 2013
			/// @since 3.9.0
			util::ParametersMap _getParametersMap() const;
			
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Conversion from generic parameters map to attributes.
			/// See https://extranet.rcsmobility.com/projects/synthese/wiki/PDF_text#Request
			//////////////////////////////////////////////////////////////////////////
			///	@param map Parameters map to interpret
			/// @author hromain
			/// @date 2013
			/// @since 3.9.0
			virtual void _setFromParametersMap(
				const util::ParametersMap& map
			);
			
			
		public:
			PDFTextService();



			//////////////////////////////////////////////////////////////////////////
			/// Display of the content generated by the function.
			/// @param stream Stream to display the content on.
			/// @param request the current request
			/// @author hromain
			/// @date 2013
			virtual util::ParametersMap run(std::ostream& stream, const server::Request& request) const;
			
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Gets if the function can be run according to the user of the session.
			/// @param session the current session
			/// @return true if the function can be run
			/// @author hromain
			/// @date 2013
			virtual bool isAuthorized(const server::Session* session) const;



			//////////////////////////////////////////////////////////////////////////
			/// Gets the Mime type of the content generated by the function.
			/// @return the Mime type of the content generated by the function
			/// @author hromain
			/// @date 2013
			virtual std::string getOutputMimeType() const;
		};
}	}

#endif // SYNTHESE_PDFTextService_H__

