Import ('s3env')

CppSynthese3LibProject(
	s3env, 's3-forum', s3env['S3VERSION'], 
	source_files = s3env.Glob ('*.cpp'),
	dependencies = [
		's3-security.cpplib',
		's3-util.cpplib',
		's3-db.cpplib',
		's3-places-list.cpplib',
		's3-interfaces.cpplib'
	]
)
