

Import ('env')

modules = ['02_db', '01_util__threads', '01_util__iostreams', '01_util', '00_tcp'];


syntheseenv = env.SyntheseEnv (modules)


syntheseenv.SyntheseBuild (syntheseenv.DefaultModuleName (), False)
