Import ('testenv')
testmoduleenv = testenv.ModuleEnv()

includes = '*.cpp'
excludes = []

# TODO : understand why link order is so important ??

testmoduleenv.AddModuleDependency ('39_carto')
testmoduleenv.AddModuleDependency ('15_env')
testmoduleenv.AddModuleDependency ('04_time')
testmoduleenv.AddModuleDependency ('01_util')
testmoduleenv.AddBoostDependency ('boost_filesystem')
testmoduleenv.AddBoostDependency ('boost_thread')
testmoduleenv.AddBoostDependency ('boost_iostreams')
testmoduleenv.AppendMultithreadConf ();


files = testmoduleenv.Glob(includes, excludes)

testmodulename = testmoduleenv.DefaultTestModuleName ()

testprogram = testmoduleenv.Program(testmodulename, files)

testmoduleenv.Test("test.passed", testprogram)


