Import ('s3env')

senv = s3env.Clone ()

prj = CppLibProject (senv, 's3-db', s3env['S3VERSION'], 
                     source_files = senv.Glob ('*.cpp'),
                     dependencies = ['s3-util-threads.shlib', 's3-util.shlib', 's3-tcp.shlib', 'sqlite3.shlib'])
senv.SConsProject (prj)

