import os.path

Import ('mainenv')
moduleenv = mainenv.ModuleEnv()

includes = '*.cpp'
excludes = []

moduleenv.AppendMultithreadConf ()

files = moduleenv.Glob(includes, excludes)

moduleenv.StaticLibrary ( moduleenv.DefaultModuleName(), files )


moduleenv = mainenv.ModuleEnv()
includes = ''
excludes = []
files = moduleenv.Glob(includes, excludes)


# Modules libs
moduleenv.AddModuleDependency ('07_lex_matcher')
moduleenv.AddModuleDependency ('01_util')
moduleenv.AddBoostDependency ('boost_filesystem')
moduleenv.AddBoostDependency ('boost_date_time')
moduleenv.AddBoostDependency ('boost_program_options')
moduleenv.AddBoostDependency ('boost_thread')
moduleenv.AppendMultithreadConf ()

moduleenv.Program ( moduleenv.DefaultModuleName(), files )



