import os.path

Import ('mainenv')
moduleenv = mainenv.ModuleEnv()

includes = '*.cpp'
excludes = []


moduleenv.AppendMultithreadConf ()


moduleenv.AddModuleDependency ('00_tcp')


files = moduleenv.Glob(includes, excludes)



moduleenv.Program(moduleenv.DefaultModuleName (), files)
