import os.path

Import ('mainenv')
moduleenv = mainenv.ModuleEnv()

includes = '*.cpp'
excludes = []


moduleenv.Append ( CPPDEFINES = ['MODULE_39'] )
moduleenv.AddModuleDependency ('39_carto')
moduleenv.AddModuleDependency ('04_time')
moduleenv.AddModuleDependency ('00_tcp')
moduleenv.AddModuleDependency ('01_util')
moduleenv.Append (LIBS = ['boost_thread'] )
moduleenv.Append (LIBS = ['boost_iostreams'] )
moduleenv.Append (LIBS = ['boost_program_options'] )
moduleenv.AppendMultithreadConf ();


moduleenv.AppendMultithreadConf ()

files = moduleenv.Glob(includes, excludes)


moduleenv.Program ( moduleenv.DefaultModuleName(), files )


