Import ('s3env')

senv = s3env.Clone ()

prj = CppLibProject (senv, 's3-security', s3env['S3VERSION'], 
                     source_files = senv.Glob ('*.cpp'),
                     dependencies = ['s3-admin.stlib', 's3-interfaces.stlib', 's3-server.stlib', 's3-dblog.stlib', 's3-db.shlib', 's3-html.shlib'])
senv.SConsProject (prj)

