Import ('s3env')

CppSynthese3LibProject(
	s3env, 's3-road', s3env['S3VERSION'], 
	source_files = s3env.Glob ('*.cpp'),
	dependencies = [
		's3-graph.cpplib',
		's3-impex.cpplib',
		's3-geography.cpplib'
	]
)
