
#include "11_interfaces/InterfaceTableSync.h"
#include "11_interfaces/InterfacePageTableSync.h"
#include "11_interfaces/InterfaceModule.h"

#include "11_interfaces/StaticValueInterfaceElement.h"
#include "11_interfaces/ParameterValueInterfaceElement.h"
#include "11_interfaces/ParameterValueInterfaceElement.h"
#include "11_interfaces/LineLabelInterfaceElement.h"
#include "11_interfaces/IncludePageInterfaceElement.h"
#include "11_interfaces/IfThenElseInterfaceElement.h"
#include "11_interfaces/GotoInterfaceElement.h"
#include "11_interfaces/PrintInterfaceElement.h"
#include "11_interfaces/DebugInterfaceElement.h"
#include "11_interfaces/CommentInterfaceElement.h"
#include "11_interfaces/FormattedNumberInterfaceElement.h"
#include "InterfaceIdInterfaceElement.h"
#include "LogicalAndInterfaceElement.h"
#include "LowerCaseInterfaceElement.h"

#include "11_interfaces/SimplePageFunction.h"
#include "11_interfaces/SetInterfaceElement.h"
#include "11_interfaces/StrLenInterfaceElement.h"
#include "11_interfaces/EqualsValueInterfaceElement.h"
#include "11_interfaces/ChrInterfaceElement.h"
#include "11_interfaces/DurationInterfacePage.h"
#include "11_interfaces/SuperiorValueInterfaceElement.h"
#include "11_interfaces/SubstrValueInterfaceElement.h"
#include "11_interfaces/AndValueInterfaceElement.h"
#include "11_interfaces/PlainCharFilterValueInterfaceElement.h"
#include "11_interfaces/DateTimeInterfacePage.h"
#include "11_interfaces/NonPredefinedInterfacePage.h"

// Registries
#include "Interface.h"
#include "InterfacePage.h"
