Import ('s3env')

senv = s3env.Clone ()

prj = CppLibProject (senv, 's3-interfaces', s3env['S3VERSION'], 
                     source_files = senv.Glob ('*.cpp'),
                     dependencies = ['s3-server.stlib', 's3-db.shlib', 's3-html.shlib'])
senv.SConsProject (prj)


