
//////////////////////////////////////////////////////////////////////////////////////////
///	PermanentThreadsService class header.
///	@file PermanentThreadsService.hpp
///	@author Camille Hue
///	@date 2013
///
///	This file belongs to the SYNTHESE project (public transportation specialized software)
///	Copyright (C) 2002 Hugues Romain - RCSmobility <contact@rcsmobility.com>
///
///	This program is free software; you can redistribute it and/or
///	modify it under the terms of the GNU General Public License
///	as published by the Free Software Foundation; either version 2
///	of the License, or (at your option) any later version.
///
///	This program is distributed in the hope that it will be useful,
///	but WITHOUT ANY WARRANTY; without even the implied warranty of
///	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
///	GNU General Public License for more details.
///
///	You should have received a copy of the GNU General Public License
///	along with this program; if not, write to the Free Software
///	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

#ifndef SYNTHESE_PermanentThreadsService_H__
#define SYNTHESE_PermanentThreadsService_H__

#include "FactorableTemplate.h"
#include "Function.h"

namespace synthese
{
	namespace server
	{
		class PermanentThread;

		//////////////////////////////////////////////////////////////////////////
		///	15.15 Function : PermanentThreadsService.
		//////////////////////////////////////////////////////////////////////////
		///	@ingroup m15Functions refFunctions
		///	@author chue
		///	@date 2013
		/// @since 3.9.0
		class PermanentThreadsService:
			public util::FactorableTemplate<server::Function,PermanentThreadsService>
		{
		public:
			static const std::string TAG_PERMANENT_THREAD;
			
		protected:
			//! \name Page parameters
			//@{
				boost::shared_ptr<const PermanentThread> _permanentThreadFilter;
			//@}
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Conversion from attributes to generic parameter maps.
			//////////////////////////////////////////////////////////////////////////
			///	@return Generated parameters map
			/// @author chue
			/// @date 2013
			/// @since 3.9.0
			util::ParametersMap _getParametersMap() const;
			
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Conversion from generic parameters map to attributes.
			//////////////////////////////////////////////////////////////////////////
			///	@param map Parameters map to interpret
			/// @author chue
			/// @date 2013
			/// @since 3.9.0
			virtual void _setFromParametersMap(
				const util::ParametersMap& map
			);
			
			
		public:
			//////////////////////////////////////////////////////////////////////////
			/// Display of the content generated by the function.
			/// @param stream Stream to display the content on.
			/// @param request the current request
			/// @author chue
			/// @date 2013
			virtual util::ParametersMap run(std::ostream& stream, const server::Request& request) const;
			
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Gets if the function can be run according to the user of the session.
			/// @param session the current session
			/// @return true if the function can be run
			/// @author chue
			/// @date 2013
			virtual bool isAuthorized(const server::Session* session) const;



			//////////////////////////////////////////////////////////////////////////
			/// Gets the Mime type of the content generated by the function.
			/// @return the Mime type of the content generated by the function
			/// @author chue
			/// @date 2013
			virtual std::string getOutputMimeType() const;
		};
}	}

#endif // SYNTHESE_PermanentThreadsService_H__

