Import ('s3env')

s3env = s3env.Clone ()
# For compiling Boost random_device.cpp, this define has to be set.
# To be removed once migrated to Boost 1.45.
s3env.Append ( CPPDEFINES = ['BOOST_RANDOM_DECL='] )

CppSynthese3LibProject(
	s3env, 's3-server', s3env['S3VERSION'],
	source_files = s3env.Glob ('*.cpp'),
	dependencies = [
		's3-util.cpplib',
		's3-security.cpplib',
		's3-dblog.cpplib',
		's3-interfaces.cpplib',
		's3-db.cpplib',
		's3-html.cpplib',
		's3-cms.cpplib'
	]
)
