import os.path

Import ('mainenv')
moduleenv = mainenv.Copy()

includes = '*.cpp'
excludes = []


files = moduleenv.Glob(includes, excludes)


moduleenv.StaticLibrary ( moduleenv.DefaultModuleName(), files )


