#!/bin/bash


source /etc/opt/rcs/s3-server.conf

test ! -x /etc/init.d/s3-server || /etc/init.d/s3-server stop

/opt/rcs/bin/spatialite $S3_SERVER_DB_FILE < /opt/rcs/s3-admin/remove.sql


test ! -x /etc/init.d/s3-server || /etc/init.d/s3-server start

VHOST_FILE=/etc/apache2/sites-available/default
grep -q "s3-admin/apache2.conf" $VHOST_FILE && ( sed --in-place "s/Include \/opt\/rcs\/s3-admin\/apache2.conf//" $VHOST_FILE && /etc/init.d/apache2 reload )
exit 0








