
//////////////////////////////////////////////////////////////////////////////////////////
/// WebPagePositionFunction class header.
///	@file WebPagePositionFunction.hpp
///	@author Hugues Romain
///	@date 2010
///
///	This file belongs to the SYNTHESE project (public transportation specialized software)
///	Copyright (C) 2002 Hugues Romain - RCS <contact@reseaux-conseil.com>
///
///	This program is free software; you can redistribute it and/or
///	modify it under the terms of the GNU General Public License
///	as published by the Free Software Foundation; either version 2
///	of the License, or (at your option) any later version.
///
///	This program is distributed in the hope that it will be useful,
///	but WITHOUT ANY WARRANTY; without even the implied warranty of
///	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
///	GNU General Public License for more details.
///
///	You should have received a copy of the GNU General Public License
///	along with this program; if not, write to the Free Software
///	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

#ifndef SYNTHESE_WebPagePositionFunction_H__
#define SYNTHESE_WebPagePositionFunction_H__

#include "FactorableTemplate.h"
#include "Function.h"

namespace synthese
{
	namespace transportwebsite
	{
		//////////////////////////////////////////////////////////////////////////
		///	56.15 Function : WebPagePositionFunction.
		///	@ingroup m56Functions refFunctions
		///	@author Hugues Romain
		///	@date 2010
		/// @since 3.1.18
		//////////////////////////////////////////////////////////////////////////
		/// Key : position
		///
		/// Parameters :
		///	<ul>
		///		<li>p : id of the page to display</li>
		///		<li>min_level (optional, default=1) : minimal level to display</li>
		///		<li>max_level (optional, default=unlimited) : maximal level to display</li>
		///		<li>For each i level :</li>
		///		<ul>
		///			<li>beginning_x (x = depth) : code to output before the item if the item does not correspond to the current displayed page</li>
		///			<li>ending_x (x = depth) : code to output after the item if the item does not correspond to the current displayed page</li>
		///			<li>beginning_selected_x (x = depth) : code to output before the item if the item corresponds to the current displayed page (default is like beginning_x)</li>
		///			<li>ending_selected_x (x = depth) : code to output after the item if the item corresponds to the current displayed page (default is like ending_x)</li>
		///		</ul>
		///	</ul>
		class WebPagePositionFunction:
			public util::FactorableTemplate<server::Function,WebPagePositionFunction>
		{
		public:
			static const std::string PARAMETER_PAGE_ID;
			static const std::string PARAMETER_MIN_DEPTH;
			static const std::string PARAMETER_MAX_DEPTH;
			static const std::string PARAMETER_BEGINNING;
			static const std::string PARAMETER_ENDING;
			static const std::string PARAMETER_BEGINNING_SELECTED;
			static const std::string PARAMETER_ENDING_SELECTED;

		protected:
			//! \name Page parameters
			//@{
				boost::shared_ptr<const WebPage> _page;
				std::size_t _minDepth;
				boost::optional<std::size_t> _maxDepth;
				std::string _beginning;
				std::string _ending;
				std::string _beginningSelected;
				std::string _endingSelected;
			//@}
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Conversion from attributes to generic parameter maps.
			///	@return Generated parameters map
			/// @author Hugues Romain
			/// @date 2010
			server::ParametersMap _getParametersMap() const;
			
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Conversion from generic parameters map to attributes.
			///	@param map Parameters map to interpret
			/// @author Hugues Romain
			/// @date 2010
			virtual void _setFromParametersMap(
				const server::ParametersMap& map
			);
			
			
		public:
			//! @name Setters
			//@{
			//	void setObject(boost::shared_ptr<const Object> value) { _object = value; }
			//@}



			//////////////////////////////////////////////////////////////////////////
			/// Display of the content generated by the function.
			/// @param stream Stream to display the content on.
			/// @param request the current request
			/// @author Hugues Romain
			/// @date 2010
			virtual void run(std::ostream& stream, const server::Request& request) const;
			
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Gets if the function can be run according to the user of the session.
			/// @param session the current session
			/// @return true if the function can be run
			/// @author Hugues Romain
			/// @date 2010
			virtual bool isAuthorized(const server::Session* session) const;



			//////////////////////////////////////////////////////////////////////////
			/// Gets the Mime type of the content generated by the function.
			/// @return the Mime type of the content generated by the function
			/// @author Hugues Romain
			/// @date 2010
			virtual std::string getOutputMimeType() const;
		};
	}
}

#endif // SYNTHESE_WebPagePositionFunction_H__
