Import ('s3env')

s3env = s3env.Clone ()
# For compiling Boost random_device.cpp, this define has to be set.
# To be removed once migrated to Boost 1.45.
s3env.Append ( CPPDEFINES = ['BOOST_RANDOM_DECL='] )

CppLibProject(
	s3env, 's3-util', s3env['S3VERSION'],
	source_files = s3env.Glob ('*.cpp'),
	dependencies = [
		'boost.cppinc',
		('boost-iostreams.cpplib',s3env['BOOSTVERSION']),
		('boost-system.cpplib',s3env['BOOSTVERSION']),
		('boost-thread.cpplib',s3env['BOOSTVERSION']),
		('boost-date-time.cpplib',s3env['BOOSTVERSION']),
		('boost-filesystem.cpplib',s3env['BOOSTVERSION']),
		('boost-regex.cpplib',s3env['BOOSTVERSION']),
		's3-framework.cpplib' # to be removed
	],
)

s3env.SubBuild ()


