
//////////////////////////////////////////////////////////////////////////////////////////
///	FreeDRTAvailableSlotsService class header.
///	@file FreeDRTAvailableSlotsService.hpp
///	@author Hugues Romain
///	@date 2012
///
///	This file belongs to the SYNTHESE project (public transportation specialized software)
///	Copyright (C) 2002 Hugues Romain - RCSmobility <contact@rcsmobility.com>
///
///	This program is free software; you can redistribute it and/or
///	modify it under the terms of the GNU General Public License
///	as published by the Free Software Foundation; either version 2
///	of the License, or (at your option) any later version.
///
///	This program is distributed in the hope that it will be useful,
///	but WITHOUT ANY WARRANTY; without even the implied warranty of
///	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
///	GNU General Public License for more details.
///
///	You should have received a copy of the GNU General Public License
///	along with this program; if not, write to the Free Software
///	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

#ifndef SYNTHESE_FreeDRTAvailableSlotsService_H__
#define SYNTHESE_FreeDRTAvailableSlotsService_H__

#include "FactorableTemplate.h"
#include "Function.h"

#include <boost/date_time/posix_time/ptime.hpp>

namespace synthese
{
	namespace geography
	{
		class Place;
	}

	namespace pt
	{
		class FreeDRTArea;
	}

	namespace resa
	{
		//////////////////////////////////////////////////////////////////////////
		///	51.15 Function : FreeDRTAvailableSlotsService.
		/// See https://extranet.rcsmobility.com/projects/synthese/wiki/
		//////////////////////////////////////////////////////////////////////////
		///	@ingroup m51Functions refFunctions
		///	@author Hugues Romain
		///	@date 2012
		/// @since 3.4.0
		class FreeDRTAvailableSlotsService:
			public util::FactorableTemplate<server::Function,FreeDRTAvailableSlotsService>
		{
		public:
			static const std::string PARAMETER_AREA_ID;
			static const std::string PARAMETER_DEPARTURE_PLACE;
			static const std::string PARAMETER_ARRIVAL_PLACE;
			static const std::string PARAMETER_MIN_DATE_TIME;
			static const std::string PARAMETER_MAX_DATE_TIME;

			static const std::string ITEM_SERVICE;
			static const std::string ITEM_SLOT;
			static const std::string ATTR_DEPARTURE_TIME;
			static const std::string ATTR_ARRIVAL_TIME;
			
		protected:
			//! \name Page parameters
			//@{
				boost::shared_ptr<const pt::FreeDRTArea> _area;
				boost::posix_time::ptime _minDateTime;
				boost::posix_time::ptime _maxDateTime;
				boost::shared_ptr<const geography::Place> _departurePlace;
				boost::shared_ptr<const geography::Place> _arrivalPlace;
			//@}
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Conversion from attributes to generic parameter maps.
			/// See https://extranet.rcsmobility.com/projects/synthese/wiki/#Request
			//////////////////////////////////////////////////////////////////////////
			///	@return Generated parameters map
			/// @author Hugues Romain
			/// @date 2012
			/// @since 3.4.0
			util::ParametersMap _getParametersMap() const;
			
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Conversion from generic parameters map to attributes.
			/// See https://extranet.rcsmobility.com/projects/synthese/wiki/#Request
			//////////////////////////////////////////////////////////////////////////
			///	@param map Parameters map to interpret
			/// @author Hugues Romain
			/// @date 2012
			/// @since 3.4.0
			virtual void _setFromParametersMap(
				const util::ParametersMap& map
			);
			
			
		public:
			//! @name Setters
			//@{
				void setArea(boost::shared_ptr<const pt::FreeDRTArea> value) { _area = value; }
			//@}



			//////////////////////////////////////////////////////////////////////////
			/// Display of the content generated by the function.
			/// @param stream Stream to display the content on.
			/// @param request the current request
			/// @author Hugues Romain
			/// @date 2012
			virtual util::ParametersMap run(std::ostream& stream, const server::Request& request) const;
			
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Gets if the function can be run according to the user of the session.
			/// @param session the current session
			/// @return true if the function can be run
			/// @author Hugues Romain
			/// @date 2012
			virtual bool isAuthorized(const server::Session* session) const;



			//////////////////////////////////////////////////////////////////////////
			/// Gets the Mime type of the content generated by the function.
			/// @return the Mime type of the content generated by the function
			/// @author Hugues Romain
			/// @date 2012
			virtual std::string getOutputMimeType() const;
		};
}	}

#endif // SYNTHESE_FreeDRTAvailableSlotsService_H__

