Import ('env')

## PROJ ##########################################################################################################################
## http://trac.osgeo.org/proj/

senv = env.Clone ()
if senv['_PLATFORM'] == 'posix':
	senv.Append ( LINKFLAGS = ['-lm'] )
CppLibProject(
	senv
	, 'proj'
	, '4.7.0a'
	, source_files = senv.Glob ('*.c', ['jniproj.c', 'nad2nad.c', 'nad2bin.c', 'geod.c', 'cs2cs.c', 'proj.c'], senv.SrcDir('src/src'), prefix='src/src/')
	, include_dir = senv.SrcDir('src/src')
	, filesrootdir = senv.SrcDir('src/src')
)

senv2 = env.Clone ()
if senv2['_PLATFORM'] == 'posix':
	senv2.Append ( LINKFLAGS = ['-lm'] )
CppBinProject(
	senv2
	, 'proj'
	, '4.7.0a'
	, source_files = ['src/src/proj.c']
	, include_dir = senv2.SrcDir('src/src')
	, filesrootdir = senv2.SrcDir('src/src')
	, dependencies = ['proj.cpplib']
)
