import os.path

Import ('mainenv')
moduleenv = mainenv.ModuleEnv()

includes = '*.cpp'
excludes = []

moduleenv.AppendMultithreadConf ()
# moduleenv.Append (CPPDEFINES = ['BOOST_DISABLE_THREADS'])


files = moduleenv.Glob(includes, excludes)


moduleenv.StaticLibrary ( moduleenv.DefaultModuleName(), files )


