import os.path

Import ('mainenv')
moduleenv = mainenv.ModuleEnv()

includes = '*.cpp'
excludes = []

moduleenv.AppendMultithreadConf ()


files = moduleenv.Glob(includes, excludes)

srcpath = Dir('.').srcnode().abspath
subdirs = os.listdir( srcpath )


# Build the list of modules to be processed
for f in subdirs:
	if not os.path.isdir (os.path.join (srcpath, f)): continue
	files.append (moduleenv.Glob (includes, excludes, os.path.join (srcpath, f)))


moduleenv.StaticLibrary ( moduleenv.DefaultModuleName(), files )


