Import ('env')

DebianPaquetProject(
	env,
	's3-admin',
	'3.2.0d',
	dependencies = [('s3-server.cppbin','3.2.0'), ('spatialite.cppbin','2.3.1')],
	extra_dependencies = [('apache2', '2.2.3-4')],
	architecture = 'all'
)
