Import ('testenv')
testmoduleenv = testenv.TestModuleEnv (includes='*.cpp', 
                                       excludes=[], 
                                       modules=['17_env_ls_sql',
                                                '15_env',
                                                '04_time',
                                                '02_db',
                                                '01_util'], 
                                       boostlibs=['boost_filesystem', 'boost_thread', 'boost_iostreams'], 
                                       withSQLite=True, 
                                       withMultithreading=True)






