Import ('s3env')

senv = s3env.Clone ()

CppTestProject (senv, 's3-util-iostreams-test', s3env['S3VERSION'], source_files = senv.Glob ('*Test.cpp'),
                     dependencies = ['s3-util-iostreams.cpplib'])
