

Import ('env')


if (env['PLATFORM'] == 'win32'):
  modules = ['01_util', '00_tcp'];
  syntheseenv = env.SyntheseEnv (modules)
  syntheseenv.SyntheseBuild (syntheseenv.DefaultModuleName (), False)



