import os.path

Import ('mainenv')
moduleenv = mainenv.Copy()

#includes = '*.cpp'
includes = ''
excludes = []

moduleenv.Append (CPPPATH = [Dir('..').srcnode().abspath] )

moduleenv.AppendMultithreadConf ()


files = moduleenv.Glob(includes, excludes)


#if (moduleenv['PLATFORM'] == 'win32'):
  # Does not compile under posix at the moment !
  #moduleenv.Program(moduleenv.DefaultModuleName (), files)
