
//////////////////////////////////////////////////////////////////////////////////////////
/// GetVehiclesService class header.
///	@file GetVehiclesService.hpp
///	@author RCSobility
///	@date 2011
///
///	This file belongs to the SYNTHESE project (public transportation specialized software)
///	Copyright (C) 2002 Hugues Romain - RCS <contact@reseaux-conseil.com>
///
///	This program is free software; you can redistribute it and/or
///	modify it under the terms of the GNU General Public License
///	as published by the Free Software Foundation; either version 2
///	of the License, or (at your option) any later version.
///
///	This program is distributed in the hope that it will be useful,
///	but WITHOUT ANY WARRANTY; without even the implied warranty of
///	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
///	GNU General Public License for more details.
///
///	You should have received a copy of the GNU General Public License
///	along with this program; if not, write to the Free Software
///	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

#ifndef SYNTHESE_GetVehiclesService_H__
#define SYNTHESE_GetVehiclesService_H__

#include "FactorableTemplate.h"
#include "Function.h"

namespace synthese
{
	namespace cms
	{
		class Webpage;
	}

	namespace pt
	{
		class CommercialLine;
	}

	namespace pt_operation
	{
		class Vehicle;

		//////////////////////////////////////////////////////////////////////////
		///	37.15 Function : GetVehiclesService.
		/// See https://extranet-rcsmobility.com/projects/synthese/wiki/Vehicles list
		//////////////////////////////////////////////////////////////////////////
		///	@ingroup m37Functions refFunctions
		///	@author RCSobility
		///	@date 2011
		/// @since 3.2.1
		class GetVehiclesService:
			public util::FactorableTemplate<server::Function,GetVehiclesService>
		{
		public:
			static const std::string PARAMETER_VEHICLE_PAGE_ID;
			static const std::string PARAMETER_LINE_ID;

			static const std::string DATA_PICTURE;
			static const std::string DATA_NAME;
			static const std::string DATA_NUMBER;
			static const std::string DATA_RANK;
			static const std::string DATA_SEATS;

		protected:
			//! \name Page parameters
			//@{
				boost::shared_ptr<cms::Webpage> _vehiclePage;
				boost::shared_ptr<pt::CommercialLine> _line;
			//@}


			//////////////////////////////////////////////////////////////////////////
			/// Conversion from attributes to generic parameter maps.
			/// See https://extranet-rcsmobility.com/projects/synthese/wiki/Vehicles list#Request
			//////////////////////////////////////////////////////////////////////////
			///	@return Generated parameters map
			/// @author RCSobility
			/// @date 2011
			/// @since 3.2.1
			server::ParametersMap _getParametersMap() const;



			//////////////////////////////////////////////////////////////////////////
			/// Conversion from generic parameters map to attributes.
			/// See https://extranet-rcsmobility.com/projects/synthese/wiki/Vehicles list#Request
			//////////////////////////////////////////////////////////////////////////
			///	@param map Parameters map to interpret
			/// @author RCSobility
			/// @date 2011
			/// @since 3.2.1
			virtual void _setFromParametersMap(
				const server::ParametersMap& map
			);


			void _displayVehicle(
				std::ostream& stream,
				const server::Request& request,
				const Vehicle& vehicle,
				std::size_t rank
			) const;


		public:
			//! @name Setters
			//@{
			//	void setObject(boost::shared_ptr<const Object> value) { _object = value; }
			//@}



			//////////////////////////////////////////////////////////////////////////
			/// Display of the content generated by the function.
			/// @param stream Stream to display the content on.
			/// @param request the current request
			/// @author RCSobility
			/// @date 2011
			virtual void run(std::ostream& stream, const server::Request& request) const;



			//////////////////////////////////////////////////////////////////////////
			/// Gets if the function can be run according to the user of the session.
			/// @param session the current session
			/// @return true if the function can be run
			/// @author RCSobility
			/// @date 2011
			virtual bool isAuthorized(const server::Session* session) const;



			//////////////////////////////////////////////////////////////////////////
			/// Gets the Mime type of the content generated by the function.
			/// @return the Mime type of the content generated by the function
			/// @author RCSobility
			/// @date 2011
			virtual std::string getOutputMimeType() const;
		};
	}
}

#endif // SYNTHESE_GetVehiclesService_H__
