Import ('env')

## SQLITE ##########################################################################################################################
## http://www.sqlite.org/

#if env.GetPlatform () == 'win32':
#   senv['MAKEDEFSYMBOLPATTERN'] = '_(sqlite3_[^ ]*)'

files = ['src/alter.c', 'src/analyze.c', 'src/attach.c', 'src/auth.c', 'src/btree.c', 'src/build.c', 'src/callback.c', 
          'src/complete.c', 'src/date.c', 'src/delete.c', 'src/expr.c', 'src/func.c', 'src/hash.c', 'src/insert.c', 'src/legacy.c', 
          'src/loadext.c', 'src/main.c', 'src/malloc.c', 'src/opcodes.c', 'src/os.c', 'src/os_os2.c', 'src/os_unix.c', 
          'src/os_win.c', 'src/pager.c', 'src/parse.c', 'src/pragma.c', 'src/prepare.c', 'src/printf.c', 'src/random.c', 
          'src/select.c', 'src/table.c', 'src/tokenize.c', 'src/trigger.c', 'src/update.c', 'src/utf.c', 'src/util.c', 
          'src/vacuum.c', 'src/vdbeapi.c', 'src/vdbeaux.c', 'src/vdbeblob.c', 'src/vdbe.c', 'src/vdbefifo.c', 'src/vdbemem.c', 
          'src/vtab.c', 'src/where.c']

CppLibProject(
	env
	, 'sqlite3'
	, '3.4.2'
	, source_files = files
	, include_dir = env.SrcDir('src')
	, filesrootdir = env.SrcDir('src')
)

