import os.path

Import ('mainenv')
moduleenv = mainenv.Copy()

includes = '*.cpp'
excludes = []

moduleenv.Append (CPPPATH = [Dir('..').srcnode().abspath] )

if (moduleenv['PLATFORM'] == 'posix'):
  moduleenv.Append (CCFLAGS= '-pthread' )
  moduleenv.Append (LIBS= ['pthread'] ) 

elif (moduleenv['PLATFORM'] == 'win32'):
  moduleenv.Append ( LIBS = ['ws2_32.lib'] )  



files = moduleenv.Glob(includes, excludes)



if (moduleenv['PLATFORM'] == 'win32'):
  # Does not compile under posix at the moment !
  moduleenv.Program(moduleenv.DefaultModuleName (), files)
