
#include "34_departures_table/DeparturesTableInterfaceElement.h"
#include "34_departures_table/DisplaySearchAdmin.h"
#include "34_departures_table/DisplayTypesAdmin.h"
#include "34_departures_table/DepartureTableRowInterfacePage.h"
#include "34_departures_table/BroadcastPointsAdmin.h"
#include "34_departures_table/BroadcastPointAdmin.h"
#include "34_departures_table/BroadcastPointTableSync.h"
#include "34_departures_table/DisplayTypeTableSync.h"
#include "34_departures_table/CreateDisplayTypeAction.h"
#include "34_departures_table/UpdateDisplayTypeAction.h"
#include "34_departures_table/ArrivalDepartureTableRight.h"
#include "34_departures_table/DisplayMaintenanceRight.h"
#include "34_departures_table/BroadcastPointsRight.h"
#include "34_departures_table/ArrivalDepartureTableLog.h"
#include "34_departures_table/BroadcastPointsDataLog.h"
#include "34_departures_table/DisplayMaintenanceLog.h"
