Import('s3env')

sources = s3env.Glob('*Test.cpp')
if not s3env['_WITH_MYSQL']:
    sources.remove('MySQLTriggerTest.cpp')

CppTestProject(
    s3env, 's3-db-test', s3env['S3VERSION'],
    source_files = sources,
    include_dir = s3env.SrcDir('#src'),
    dependencies = ['s3-db.cpplib']
)
