Import ('testenv')
testmoduleenv = testenv.Copy()

includes = '*.cpp'
excludes = []


files = testmoduleenv.Glob(includes, excludes)


testmoduleenv.Library(testmoduleenv.DefaultTestModuleName (), files)

