Import ('s3env')

senv = s3env.Clone ()

prj = CppLibProject (senv, 's3-util-threads', s3env['S3VERSION'], 
                     source_files = senv.Glob ('*.cpp'),
                     dependencies = ['s3-util.shlib'])
senv.SConsProject (prj)



