Import ('s3env')

CppLibProject(
	s3env,
	's3-env',
	s3env['S3VERSION'],
	source_files = s3env.Glob ('*.cpp'),
	dependencies = [
		's3-security.cpplib',
		's3-util.cpplib',
		's3-interfaces.cpplib',
		's3-graph.cpplib',
		's3-geometry.cpplib',
		's3-db.cpplib',
		's3-time.cpplib',
		's3-messages.cpplib',
		's3-pt.cpplib',
		's3-road.cpplib'
	]
)
