Import ('s3env')

senv = s3env.Clone ()

prj = CppLibProject (senv, 's3-env', s3env['S3VERSION'], 
                     source_files = senv.Glob ('*.cpp'),
                     dependencies = ['s3-security.stlib', 's3-interfaces.stlib', 's3-lex-matcher.shlib', 's3-geometry.shlib', 's3-db.shlib', 's3-time.shlib'])
senv.SConsProject (prj)
