Import ('s3env')

CppSynthese3LibProject(
	s3env,
	's3-impex',
	s3env['S3VERSION'], 
	source_files = s3env.Glob ('*.cpp'),
	dependencies = ['s3-server.cpplib', 's3-db.cpplib', 's3-util-iostreams.cpplib', 'boost.cppinc', 'boost-regex.cpplib'],
)
