Import ('s3env')

senv = s3env.Clone ()

prj = CppLibProject (senv, 's3-impex', s3env['S3VERSION'], 
                     source_files = senv.Glob ('*.cpp'),
                     dependencies = ['s3-env.stlib', 's3-geography.shlib', 's3-db.shlib', 's3-util-iostreams.shlib', 'boost-regex.shlib'])
senv.SConsProject (prj)

