
//////////////////////////////////////////////////////////////////////////////////////////
/// SVNStorageFunction class header.
///	@file SVNStorageFunction.hpp
///	@author Sylvai Pasche
///	@date 2012
///
///	This file belongs to the SYNTHESE project (public transportation specialized software)
///	Copyright (C) 2002 Hugues Romain - RCSmobility <contact@rcsmobility.com>
///
///	This program is free software; you can redistribute it and/or
///	modify it under the terms of the GNU General Public License
///	as published by the Free Software Foundation; either version 2
///	of the License, or (at your option) any later version.
///
///	This program is distributed in the hope that it will be useful,
///	but WITHOUT ANY WARRANTY; without even the implied warranty of
///	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
///	GNU General Public License for more details.
///
///	You should have received a copy of the GNU General Public License
///	along with this program; if not, write to the Free Software
///	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

#ifndef SYNTHESE_SVNStorageFunction_H__
#define SYNTHESE_SVNStorageFunction_H__

#include "FactorableTemplate.h"
#include "Function.h"

namespace synthese
{
	namespace impex
	{
		//////////////////////////////////////////////////////////////////////////
		///	16.15 Function : SVNStorageFunction.
		/// See https://extranet.rcsmobility.com/projects/synthese/wiki/SVN_Storage
		//////////////////////////////////////////////////////////////////////////
		///	@ingroup m16Functions refFunctions
		///	@author Sylvain Pasche
		///	@date 2012
		/// @since 3.3.0
		class SVNStorageFunction:
			public util::FactorableTemplate<server::Function,SVNStorageFunction>
		{
		public:
			static const std::string PARAMETER_DATASOURCE_ID;
			static const std::string PARAMETER_OBJECT_ID;
			static const std::string PARAMETER_EXPORT_PATH;
			static const std::string PARAMETER_CHECKOUT_PATH;
			static const std::string PARAMETER_URL;
			static const std::string PARAMETER_USERNAME;
			static const std::string PARAMETER_PASSWORD;
			static const std::string PARAMETER_UPDATE;
			static const std::string PARAMETER_COMMIT;
			static const std::string PARAMETER_COMMIT_MESSAGE;
			static const std::string PARAMETER_VERBOSE;

			static const std::string VALUE_SUCCESS;
			
		protected:
			//! \name Page parameters
			//@{
				std::string _datasourceId;
				std::string _objectId;
				std::string _exportPath;
				std::string _checkoutPath;
				std::string _url;
				std::string _username;
				std::string _password;
				bool _update;
				bool _commit;
				std::string _commitMessage;
				bool _verbose;
			//@}


		public:
			//////////////////////////////////////////////////////////////////////////
			/// Conversion from attributes to generic parameter maps.
			/// See https://extranet.rcsmobility.com/projects/synthese/wiki/SVN_Storage#Request
			//////////////////////////////////////////////////////////////////////////
			///	@return Generated parameters map
			/// @author Sylvain Pasche
			/// @date 2012
			/// @since 3.3.0
			util::ParametersMap _getParametersMap() const;
			
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Conversion from generic parameters map to attributes.
			/// See https://extranet.rcsmobility.com/projects/synthese/wiki/SVN_Storage#Request
			//////////////////////////////////////////////////////////////////////////
			///	@param map Parameters map to interpret
			/// @author Sylvain Pasche
			/// @date 2012
			/// @since 3.3.0
			virtual void _setFromParametersMap(const util::ParametersMap& map);



			//////////////////////////////////////////////////////////////////////////
			/// Display of the content generated by the function.
			/// @param stream Stream to display the content on.
			/// @param request the current request
			/// @author Sylvain Pasche
			/// @date 2012
			virtual util::ParametersMap run(std::ostream& stream, const server::Request& request) const;
			
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Gets if the function can be run according to the user of the session.
			/// @param session the current session
			/// @return true if the function can be run
			/// @author Sylvain Pasche
			/// @date 2012
			virtual bool isAuthorized(const server::Session* session) const;



			//////////////////////////////////////////////////////////////////////////
			/// Gets the Mime type of the content generated by the function.
			/// @return the Mime type of the content generated by the function
			/// @author Sylvain Pasche
			/// @date 2012
			virtual std::string getOutputMimeType() const;
		};
	}
}

#endif // SYNTHESE_SVNStorageFunction_H__

