
//////////////////////////////////////////////////////////////////////////////////////////
/// CheckLineCalendar class header.
///	@file CheckLineCalendarFunction.hpp
///	@author Hugues Romain
///	@date 2010
///
///	This file belongs to the SYNTHESE project (public transportation specialized software)
///	Copyright (C) 2002 Hugues Romain - RCSmobility <contact@rcsmobility.com>
///
///	This program is free software; you can redistribute it and/or
///	modify it under the terms of the GNU General Public License
///	as published by the Free Software Foundation; either version 2
///	of the License, or (at your option) any later version.
///
///	This program is distributed in the hope that it will be useful,
///	but WITHOUT ANY WARRANTY; without even the implied warranty of
///	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
///	GNU General Public License for more details.
///
///	You should have received a copy of the GNU General Public License
///	along with this program; if not, write to the Free Software
///	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

#ifndef SYNTHESE_CheckLineCalendar_H__
#define SYNTHESE_CheckLineCalendar_H__

#include "FactorableTemplate.h"
#include "Function.h"
#include <boost/date_time/date_duration.hpp>

namespace synthese
{
	namespace pt
	{
		class CommercialLine;
	}

	namespace pt
	{
		//////////////////////////////////////////////////////////////////////////
		/// 35.15 Checks if the specified commercial line runs every day of its calendar template.
		/// See https://extranet.rcsmobility.com/projects/synthese/wiki/Line_calendar_check
		//////////////////////////////////////////////////////////////////////////
		///	@author Hugues Romain
		///	@date 2010
		///	@ingroup m35Functions refFunctions
		/// @since 3.1.16
		class CheckLineCalendarFunction:
			public util::FactorableTemplate<server::Function,CheckLineCalendarFunction>
		{
		public:
			static const std::string PARAMETER_DURATION;

		protected:
			//! \name Page parameters
			//@{
				boost::shared_ptr<const pt::CommercialLine> _line;
				boost::gregorian::date_duration _duration;
			//@}


			//////////////////////////////////////////////////////////////////////////
			/// Conversion from attributes to generic parameter maps.
			///	@return Generated parameters map
			/// @author Hugues Romain
			/// @date 2010
			util::ParametersMap _getParametersMap() const;



			//////////////////////////////////////////////////////////////////////////
			/// Conversion from generic parameters map to attributes.
			///	@param map Parameters map to interpret
			/// @author Hugues Romain
			/// @date 2010
			virtual void _setFromParametersMap(
				const util::ParametersMap& map
			);


		public:
			//! @name Setters
			//@{
				void setLine(boost::shared_ptr<const pt::CommercialLine> value) {_line = value; }
			//@}



			//////////////////////////////////////////////////////////////////////////
			/// Display of the content generated by the function.
			/// @param stream Stream to display the content on.
			/// @param request the current request
			/// @author Hugues Romain
			/// @date 2010
			virtual util::ParametersMap run(
				std::ostream& stream,
				const server::Request& request
			) const;



			//////////////////////////////////////////////////////////////////////////
			/// Gets if the function can be run according to the user of the session.
			/// @param session the current session
			/// @return true if the function can be run
			/// @author Hugues Romain
			/// @date 2010
			virtual bool isAuthorized(const server::Session* session) const;



			//////////////////////////////////////////////////////////////////////////
			/// Gets the Mime type of the content generated by the function.
			/// @return the Mime type of the content generated by the function
			/// @author Hugues Romain
			/// @date 2010
			virtual std::string getOutputMimeType() const;


			CheckLineCalendarFunction();
		};
	}
}

#endif // SYNTHESE_CheckLineCalendar_H__
