
//////////////////////////////////////////////////////////////////////////////////////////
/// PhysicalStopsCSVExportFunction class header.
///	@file PhysicalStopsCSVExportFunction.h
///	@author Hugues
///	@date 2010
///
///	This file belongs to the SYNTHESE project (public transportation specialized software)
///	Copyright (C) 2002 Hugues Romain - RCSmobility <contact@rcsmobility.com>
///
///	This program is free software; you can redistribute it and/or
///	modify it under the terms of the GNU General Public License
///	as published by the Free Software Foundation; either version 2
///	of the License, or (at your option) any later version.
///
///	This program is distributed in the hope that it will be useful,
///	but WITHOUT ANY WARRANTY; without even the implied warranty of
///	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
///	GNU General Public License for more details.
///
///	You should have received a copy of the GNU General Public License
///	along with this program; if not, write to the Free Software
///	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

#ifndef SYNTHESE_PhysicalStopsCSVExportFunction_H__
#define SYNTHESE_PhysicalStopsCSVExportFunction_H__

#include "FactorableTemplate.h"
#include "Function.h"

#include <geos/geom/Envelope.h>
#include <boost/optional.hpp>

namespace synthese
{
	class CoordinatesSystem;

	namespace pt
	{
		/** PhysicalStopsCSVExportFunction Function class.
			@author Hugues Romain
			@date 2010
			@ingroup m35Functions refFunctions
		*/
		class PhysicalStopsCSVExportFunction:
			public util::FactorableTemplate<server::Function,PhysicalStopsCSVExportFunction>
		{
		public:
			static const std::string PARAMETER_BBOX;
			static const std::string PARAMETER_SRID;

		protected:
			//! \name Page parameters
			//@{
				boost::optional<geos::geom::Envelope> _bbox;
				const CoordinatesSystem* _coordinatesSystem;
			//@}


			//////////////////////////////////////////////////////////////////////////
			/// Conversion from attributes to generic parameter maps.
			///	@return Generated parameters map
			/// @author Hugues
			/// @date 2010
			util::ParametersMap _getParametersMap() const;



			//////////////////////////////////////////////////////////////////////////
			/// Conversion from generic parameters map to attributes.
			///	@param map Parameters map to interpret
			/// @author Hugues
			/// @date 2010
			virtual void _setFromParametersMap(
				const util::ParametersMap& map
			);


		public:

			//////////////////////////////////////////////////////////////////////////
			/// Gets the default name of the generated file.
			/// @return default name of the generated file
			///    empty = display directly the result in the browser
			virtual std::string getFileName() const;


			//////////////////////////////////////////////////////////////////////////
			/// Display of the content generated by the function.
			/// @param stream Stream to display the content on.
			/// @author Hugues
			/// @date 2010
			virtual util::ParametersMap run(
				std::ostream& stream,
				const server::Request& request
			) const;



			//////////////////////////////////////////////////////////////////////////
			/// Gets if the function can be run according to the user of the session.
			/// @return true if the function can be run
			/// @author Hugues
			/// @date 2010
			virtual bool isAuthorized(const server::Session* session) const;



			//////////////////////////////////////////////////////////////////////////
			/// Gets the Mime type of the content generated by the function.
			/// @return the Mime type of the content generated by the function
			/// @author Hugues
			/// @date 2010
			virtual std::string getOutputMimeType() const;
		};
	}
}

#endif // SYNTHESE_PhysicalStopsCSVExportFunction_H__
