
//////////////////////////////////////////////////////////////////////////////////////////
/// PTObjectInformationFunction class header.
///	@file PTObjectInformationFunction.hpp
///	@author Hugues Romain
///	@date 2010
///
///	This file belongs to the SYNTHESE project (public transportation specialized software)
///	Copyright (C) 2002 Hugues Romain - RCS <contact@reseaux-conseil.com>
///
///	This program is free software; you can redistribute it and/or
///	modify it under the terms of the GNU General Public License
///	as published by the Free Software Foundation; either version 2
///	of the License, or (at your option) any later version.
///
///	This program is distributed in the hope that it will be useful,
///	but WITHOUT ANY WARRANTY; without even the implied warranty of
///	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
///	GNU General Public License for more details.
///
///	You should have received a copy of the GNU General Public License
///	along with this program; if not, write to the Free Software
///	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

#ifndef SYNTHESE_PTObjectInformationFunction_H__
#define SYNTHESE_PTObjectInformationFunction_H__

#include "FactorableTemplate.h"
#include "Function.h"

namespace synthese
{
	namespace pt
	{
		class TransportNetwork;
		class CommercialLine;
		class Line;
		class StopArea;

		//////////////////////////////////////////////////////////////////////////
		///	35.15 Function : PTObjectInformationFunction.
		///	@ingroup m35Functions refFunctions
		///	@author Hugues Romain
		///	@date 2010
		/// @since 3.1.16
		//////////////////////////////////////////////////////////////////////////
		/// Key : PTObjectInformationFunction
		///
		/// Parameters :
		///	<ul>
		///		<li>roid : id of the object to extract the infromations from.
		///		The object can be a service, a route, a line, a network.</li>
		///		<li>info : code of the information to extract (see above)</li>
		///	</ul>
		///
		/// Information codes :
		///	<ul>
		///		<li>if the object is a network</li>
		///		<ul>
		///			<li>name : name of the network</li>
		///		</ul>
		///		<li>if the object is a line</li>
		///		<ul>
		///			<li>short_name : short name of the line</li>
		///			<li>name : name of the line</li>
		///			<li>network_id : id of the network</li>
		///			<li>style : style of the line</li>
		///			<li>image : image of the line</li>
		///		</ul>
		///		<li>if the object is a route</li>
		///		<ul>
		///			<li>line_id : id of the line</li>
		///			<li>origin_city_name : name of the city of the origin stop</li>
		///			<li>origin_stop_name : name of the origin stop</li>
		///			<li>destination_city_name : name of the city of the destination stop</li>
		///			<li>destination_stop_name : name of the destination stop</li>
		///		</ul>
		///		<li>if the object is a commercial stop</li>
		///		<ul>
		///			<li>city_name : name of the city of the stop</li>
		///			<li>name : name of the stop</li>
		///		</ul>
		class PTObjectInformationFunction:
			public util::FactorableTemplate<server::Function,PTObjectInformationFunction>
		{
		public:
			static const std::string PARAMETER_INFO;
			
		protected:
			//! \name Page parameters
			//@{
				std::string _info;
				boost::shared_ptr<const TransportNetwork> _network;
				boost::shared_ptr<const CommercialLine> _line;
				boost::shared_ptr<const Line> _route;
				boost::shared_ptr<const StopArea> _stop;
			//@}
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Conversion from attributes to generic parameter maps.
			///	@return Generated parameters map
			/// @author Hugues Romain
			/// @date 2010
			server::ParametersMap _getParametersMap() const;
			
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Conversion from generic parameters map to attributes.
			///	@param map Parameters map to interpret
			/// @author Hugues Romain
			/// @date 2010
			virtual void _setFromParametersMap(
				const server::ParametersMap& map
			);
			
			
		public:
			//////////////////////////////////////////////////////////////////////////
			/// Display of the content generated by the function.
			/// @param stream Stream to display the content on.
			/// @param request the current request
			/// @author Hugues Romain
			/// @date 2010
			virtual void run(std::ostream& stream, const server::Request& request) const;
			
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Gets if the function can be run according to the user of the session.
			/// @param session the current session
			/// @return true if the function can be run
			/// @author Hugues Romain
			/// @date 2010
			virtual bool isAuthorized(const server::Session* session) const;



			//////////////////////////////////////////////////////////////////////////
			/// Gets the Mime type of the content generated by the function.
			/// @return the Mime type of the content generated by the function
			/// @author Hugues Romain
			/// @date 2010
			virtual std::string getOutputMimeType() const;
		};
	}
}

#endif // SYNTHESE_PTObjectInformationFunction_H__
