
//////////////////////////////////////////////////////////////////////////////////////////
/// PTRoutesListFunction class header.
///	@file PTRoutesListFunction.hpp
///	@author Hugues Romain
///	@date 2010
///
///	This file belongs to the SYNTHESE project (public transportation specialized software)
///	Copyright (C) 2002 Hugues Romain - RCS <contact@reseaux-conseil.com>
///
///	This program is free software; you can redistribute it and/or
///	modify it under the terms of the GNU General Public License
///	as published by the Free Software Foundation; either version 2
///	of the License, or (at your option) any later version.
///
///	This program is distributed in the hope that it will be useful,
///	but WITHOUT ANY WARRANTY; without even the implied warranty of
///	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
///	GNU General Public License for more details.
///
///	You should have received a copy of the GNU General Public License
///	along with this program; if not, write to the Free Software
///	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

#ifndef SYNTHESE_PTRoutesListFunction_H__
#define SYNTHESE_PTRoutesListFunction_H__

#include "FactorableTemplate.h"
#include "FunctionWithSite.h"

namespace synthese
{
	namespace pt
	{
		class CommercialLine;
	}

	namespace pt
	{
		class PTRoutesListItemInterfacePage;

		/** Lists the routes of a line.
			@author Hugues Romain
			@date 2010
			@since 3.1.16
			@ingroup m35Functions refFunctions

			Parameters :
			<ul>
				<li>roid : id of the line to display</li>
				<li>msr : do not display a route if an other route follows the same stops list in the same order (the comparison is done on connection places and not physical stops)</li>
				<li>mir : do not display a route if an other route serves the same stops list in the same order even if the other route serves other stops before, after, and inside</li>
			</ul>
		*/
		class PTRoutesListFunction:
			public util::FactorableTemplate<transportwebsite::FunctionWithSite<false>,PTRoutesListFunction>
		{
		public:
			static const std::string PARAMETER_MERGE_SAME_ROUTES;
			static const std::string PARAMETER_MERGE_INCLUDING_ROUTES;
			
		protected:
			//! \name Page parameters
			//@{
				boost::shared_ptr<const pt::CommercialLine> _line;
				const PTRoutesListItemInterfacePage* _page;
				bool _mergeSameRoutes;
				bool _mergeIncludingRoutes;
			//@}
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Conversion from attributes to generic parameter maps.
			///	@return Generated parameters map
			/// @author Hugues Romain
			/// @date 2010
			server::ParametersMap _getParametersMap() const;
			
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Conversion from generic parameters map to attributes.
			///	@param map Parameters map to interpret
			/// @author Hugues Romain
			/// @date 2010
			virtual void _setFromParametersMap(
				const server::ParametersMap& map
			);
			
			
		public:
			//! @name Setters
			//@{
				void setLine(boost::shared_ptr<const pt::CommercialLine> value) { _line = value; }
			//@}



			//////////////////////////////////////////////////////////////////////////
			/// Display of the content generated by the function.
			/// @param stream Stream to display the content on.
			/// @param request the current request
			/// @author Hugues Romain
			/// @date 2010
			virtual void run(std::ostream& stream, const server::Request& request) const;
			
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Gets if the function can be run according to the user of the session.
			/// @param session the current session
			/// @return true if the function can be run
			/// @author Hugues Romain
			/// @date 2010
			virtual bool isAuthorized(const server::Session* session) const;



			//////////////////////////////////////////////////////////////////////////
			/// Gets the Mime type of the content generated by the function.
			/// @return the Mime type of the content generated by the function
			/// @author Hugues Romain
			/// @date 2010
			virtual std::string getOutputMimeType() const;
		};
	}
}

#endif // SYNTHESE_PTRoutesListFunction_H__
