
//////////////////////////////////////////////////////////////////////////////////////////
/// ServiceQuotasListService class header.
///	@file ServiceQuotasListService.hpp
///	@author Gael Sauvanet
///	@date 2012
///
///	This file belongs to the SYNTHESE project (public transportation specialized software)
///	Copyright (C) 2002 Hugues Romain - RCSmobility <contact@rcsmobility.com>
///
///	This program is free software; you can redistribute it and/or
///	modify it under the terms of the GNU General Public License
///	as published by the Free Software Foundation; either version 2
///	of the License, or (at your option) any later version.
///
///	This program is distributed in the hope that it will be useful,
///	but WITHOUT ANY WARRANTY; without even the implied warranty of
///	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
///	GNU General Public License for more details.
///
///	You should have received a copy of the GNU General Public License
///	along with this program; if not, write to the Free Software
///	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

#ifndef SYNTHESE_ServiceQuotasListService_H__
#define SYNTHESE_ServiceQuotasListService_H__

#include "FactorableTemplate.h"
#include "FunctionWithSite.h"

#include <boost/date_time/gregorian/greg_date.hpp>

namespace synthese
{
	namespace pt
	{
		class ScheduledService;

		//////////////////////////////////////////////////////////////////////////
		///	35.15 Function : ServiceQuotasListService.
		/// See https://extranet.rcsmobility.com/projects/synthese/wiki/Service_quotas_list
		//////////////////////////////////////////////////////////////////////////
		///	@ingroup m35Functions refFunctions
		///	@author Gael Sauvanet
		///	@date 2012
		/// @since 3.3.0
		class ServiceQuotasListService:
			public util::FactorableTemplate<cms::FunctionWithSite<false>, ServiceQuotasListService>
		{
		public:
			static const std::string PARAMETER_SERVICE_ID;
			static const std::string PARAMETER_MIN_DATE;
			static const std::string PARAMETER_MAX_DATE;
			static const std::string PARAMETER_PAGE_ID;

			static const std::string TAG_SERVICE_QUOTA;
			static const std::string TAG_SERVICE_QUOTAS;

		protected:
			//! \name Parameters
			//@{
				boost::shared_ptr<ScheduledService> _service;
				boost::gregorian::date _minDate;
				boost::gregorian::date _maxDate;
				boost::shared_ptr<const cms::Webpage> _page;
			//@}


			//////////////////////////////////////////////////////////////////////////
			/// Conversion from attributes to generic parameter maps.
			/// See https://extranet.rcsmobility.com/projects/synthese/wiki/Service_quotas_list#Request
			//////////////////////////////////////////////////////////////////////////
			///	@return Generated parameters map
			/// @author Gael Sauvanet
			/// @date 2012
			/// @since 3.3.0
			util::ParametersMap _getParametersMap() const;



			//////////////////////////////////////////////////////////////////////////
			/// Conversion from generic parameters map to attributes.
			/// See https://extranet.rcsmobility.com/projects/synthese/wiki/Service_quotas_list#Request
			//////////////////////////////////////////////////////////////////////////
			///	@param map Parameters map to interpret
			/// @author Gael Sauvanet
			/// @date 2012
			/// @since 3.3.0
			virtual void _setFromParametersMap(
				const util::ParametersMap& map
				);


		public:
			ServiceQuotasListService();



			//////////////////////////////////////////////////////////////////////////
			/// Display of the content generated by the function.
			/// @param stream Stream to display the content on.
			/// @param request the current request
			/// @author Gael Sauvanet
			/// @date 2012
			virtual util::ParametersMap run(std::ostream& stream, const server::Request& request) const;



			//////////////////////////////////////////////////////////////////////////
			/// Gets if the function can be run according to the user of the session.
			/// @param session the current session
			/// @return true if the function can be run
			/// @author Gael Sauvanet
			/// @date 2012
			virtual bool isAuthorized(const server::Session* session) const;



			//////////////////////////////////////////////////////////////////////////
			/// Gets the Mime type of the content generated by the function.
			/// @return the Mime type of the content generated by the function
			/// @author Gael Sauvanet
			/// @date 2012
			virtual std::string getOutputMimeType() const;
		};
}	}

#endif // SYNTHESE_ServiceQuotasListService_H__
