
//////////////////////////////////////////////////////////////////////////////////////////
/// PTRoutePlannerInputFunction class header.
///	@file PTRoutePlannerInputFunction.hpp
///	@author Hugues Romain
///	@date 2010
///
///	This file belongs to the SYNTHESE project (public transportation specialized software)
///	Copyright (C) 2002 Hugues Romain - RCSmobility <contact@rcsmobility.com>
///
///	This program is free software; you can redistribute it and/or
///	modify it under the terms of the GNU General Public License
///	as published by the Free Software Foundation; either version 2
///	of the License, or (at your option) any later version.
///
///	This program is distributed in the hope that it will be useful,
///	but WITHOUT ANY WARRANTY; without even the implied warranty of
///	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
///	GNU General Public License for more details.
///
///	You should have received a copy of the GNU General Public License
///	along with this program; if not, write to the Free Software
///	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

#ifndef SYNTHESE_PTRoutePlannerInputFunction_H__
#define SYNTHESE_PTRoutePlannerInputFunction_H__

#include "FactorableTemplate.h"
#include "Function.h"

namespace synthese
{
	namespace cms
	{
		class Webpage;
	}

	namespace pt_website
	{
		class PTServiceConfig;
	}

	namespace pt_journey_planner
	{
		//////////////////////////////////////////////////////////////////////////
		///	53.15 Function : PTRoutePlannerInputFunction.
		///	@ingroup m53Functions refFunctions
		///	@author Hugues Romain
		///	@date 2010
		/// @since 3.1.16
		//////////////////////////////////////////////////////////////////////////
		/// Key : PTRoutePlannerInputFunction
		///
		/// Parameters :
		///	<ul>
		///		<li>field : field to generate</li>
		///		<ul>
		///			<li>origin_city</li>
		///			<li>destination_city</li>
		///			<li>origin_place</li>
		///			<li>destination_place</li>
		///			<li>date_list</li>
		///			<li>period</li>
		///		</ul>
		///		<li>value : default value</li>
		///		<li>html : html code to add in the input field</li>
		///		<li>date_display_template : cms page to use to display a date (used by date_list only)</li>
		///	</ul>
		class PTRoutePlannerInputFunction:
			public util::FactorableTemplate<server::Function,PTRoutePlannerInputFunction>
		{
		public:
			static const std::string PARAMETER_FIELD;
			static const std::string PARAMETER_VALUE;
			static const std::string PARAMETER_HTML;
			static const std::string PARAMETER_DATE_DISPLAY_TEMPLATE;
			static const std::string PARAMETER_CONFIG_ID;

			static const std::string FIELD_ORIGIN_CITY;
			static const std::string FIELD_DESTINATION_CITY;
			static const std::string FIELD_ORIGIN_PLACE;
			static const std::string FIELD_DESTINATION_PLACE;
			static const std::string FIELD_DATE_LIST;
			static const std::string FIELD_PERIOD;

		protected:
			//! \name Page parameters
			//@{
				std::string _field;
				std::string _value;
				std::string _html;
				const pt_website::PTServiceConfig* _config;
				boost::shared_ptr<const cms::Webpage> _dateDisplayTemplate;
			//@}


			//////////////////////////////////////////////////////////////////////////
			/// Conversion from attributes to generic parameter maps.
			///	@return Generated parameters map
			/// @author Hugues Romain
			/// @date 2010
			util::ParametersMap _getParametersMap() const;



			//////////////////////////////////////////////////////////////////////////
			/// Conversion from generic parameters map to attributes.
			///	@param map Parameters map to interpret
			/// @author Hugues Romain
			/// @date 2010
			virtual void _setFromParametersMap(
				const util::ParametersMap& map
			);


		public:
			PTRoutePlannerInputFunction();


			//////////////////////////////////////////////////////////////////////////
			/// Display of the content generated by the function.
			/// @param stream Stream to display the content on.
			/// @param request the current request
			/// @author Hugues Romain
			/// @date 2010
			virtual util::ParametersMap run(std::ostream& stream, const server::Request& request) const;



			//////////////////////////////////////////////////////////////////////////
			/// Gets if the function can be run according to the user of the session.
			/// @param session the current session
			/// @return true if the function can be run
			/// @author Hugues Romain
			/// @date 2010
			virtual bool isAuthorized(const server::Session* session) const;



			//////////////////////////////////////////////////////////////////////////
			/// Gets the Mime type of the content generated by the function.
			/// @return the Mime type of the content generated by the function
			/// @author Hugues Romain
			/// @date 2010
			virtual std::string getOutputMimeType() const;
		};
}	}

#endif // SYNTHESE_PTRoutePlannerInputFunction_H__
