function new_event_click(){
  $('#new_event_modal').modal('show');
  return false;
}

function copy_event_click(){
  $('#copy_event_form_actionParamtpl_AUTOGENERATEDFIELDID').val($(this).attr('element_id'));
  $('#copy_event_name_field').val('Copie de '+ $(this).attr('element_name'));
  $('#copy_event_modal').modal('show');
  return false;
}

$(function(){
  $('#new_event_link').click(new_event_click);
  $('.copy_event_link').click(copy_event_click);
});