import os.path

Import ('mainenv')
moduleenv = mainenv.Copy()

includes = ''
excludes = []

moduleenv.AppendMultithreadConf ()

files = moduleenv.Glob(includes, excludes)


moduleenv.StaticLibrary ( moduleenv.DefaultModuleName(), files )


