import os.path

Import ('mainenv')
moduleenv = mainenv.ModuleEnv()

includes = 'SQLite*.cpp'
excludes = []

moduleenv.AppendMultithreadConf ()

files = moduleenv.Glob(includes, excludes)


moduleenv.StaticLibrary ( moduleenv.DefaultModuleName(), files )


