import os.path

Import ('mainenv')
moduleenv = mainenv.ModuleEnv()

includes = '*.cpp'
excludes = []

moduleenv.AppendMultithreadConf ()

files = moduleenv.Glob(includes, excludes)


moduleenv.StaticLibrary ( moduleenv.DefaultModuleName(), files )



moduleenv = mainenv.ModuleEnv()



# Modules libs
moduleenv.AddModuleDependency ('02_db')
moduleenv.AddModuleDependency ('01_util')
moduleenv.AddModuleDependency ('00_tcp')
moduleenv.AddBoostDependency ('boost_filesystem')
moduleenv.AddBoostDependency ('boost_date_time')
moduleenv.AddBoostDependency ('boost_program_options')
moduleenv.AddBoostDependency ('boost_thread')
moduleenv.AddBoostDependency ('boost_iostreams')
moduleenv.AddSQLiteDependency ()
moduleenv.AppendMultithreadConf ()

moduleenv.Program ( moduleenv.DefaultModuleName (), files )



