function click_remove()
{
  $('#remove_form_actionParamoi_AUTOGENERATEDFIELDID').val($(this).attr('element_id'));
  $('#remove_name').html($(this).attr('element_name'));
  $('#remove_modal').modal('show');
}

function click_rename()
{
  $('#rename_name_field').val($(this).attr('element_name'));
  $('#rename_form_actionParamsid_AUTOGENERATEDFIELDID').val($(this).attr('element_id'));
  $('#rename_modal').modal('show');
  $('#rename_name_field').focus();
}

function click_move()
{
  $('#move_name').html($(this).attr('element_name'));
  $('#move_form_actionParamsid_AUTOGENERATEDFIELDID').val($(this).attr('element_id'));
  $('#move_form_actionParamfi_AUTOGENERATEDFIELDID').val($('.move_element[active="1"]').attr('element_id'));
  $('.move_element').removeClass('active');
  $('.move_element[active="1"]').addClass('active');
  $('#move_modal').modal('show');
}

function move_element_click()
{
  $('#move_form_actionParamfi_AUTOGENERATEDFIELDID').val($(this).attr('element_id'));
  $('.move_element').removeClass('active');
  $(this).addClass('active');
  return false;
}

function new_dir_link_click()
{
  $('#newdir').modal('show');
  return false;
}

function rename_dir_link_click()
{
  $('#renamedir').modal('show');
  return false;
}

function remove_dir_link_click()
{
  $('#removedir').modal('show');
  return false;
}

$(function(){
  $('.remove_link').click(click_remove);
  $('.rename_link').click(click_rename);
  $('.move_link').click(click_move);
  $('.move_element').click(move_element_click);
  $('#new_dir_link').click(new_dir_link_click);
  $('#rename_dir_link').click(rename_dir_link_click);
  $('#remove_dir_link').click(remove_dir_link_click);
});


function copyContent(contentRank)
{
 addMessageTab({
    id: 0,
    title: "Copie de " + document.getElementById('title_'+ contentRank).value,
    content: tinyMCE.get('tinymce_'+ contentRank).getContent(),
    level: document.getElementById('level_'+ contentRank).value,
    displayDuration: document.getElementById('displayDuration_'+ contentRank).value,
    repeat_interval: document.getElementById('repeat_interval_'+ contentRank).value,
    with_ack: document.getElementById('with_ack_'+ contentRank).value,
    multiple_stops: document.getElementById('multiple_stops_'+ contentRank).value,
    play_tts: document.getElementById('play_tts_'+ contentRank).value,
    light: document.getElementById('light_'+ contentRank).value,
    alternatives: {},
    recipients: {}
  });
  tinyMCE.execCommand('mceAddControl', false, 'tinymce_'+ (nextMessageRank-1));
  $('#tab_m_'+(nextMessageRank-1)).tab('show');
  current_message_rank=nextMessageRank-1;
  tinyMCE.execCommand('mceFocus', false, 'tinymce_'+ (nextMessageRank-1));
  document.getElementById('tab_key').value = "m_"+ current_message_rank;
  activateForm();
  return false;

}