Import ('s3env')

CppLibProject(
	s3env, 's3-route-planner', s3env['S3VERSION'], 
	source_files = s3env.Glob ('*.cpp'),
	dependencies = [
		's3-pt.cpplib',
		's3-resa.cpplib',
		's3-messages.cpplib'
	]
)
