Import ('s3env')

senv = s3env.Clone ()

prj = CppLibProject (senv, 's3-route-planner', s3env['S3VERSION'], 
                     source_files = senv.Glob ('*.cpp'),
                     dependencies = ['s3-env.shlib', 's3-resa.stlib', 's3-messages.stlib'])
senv.SConsProject (prj)

