Import ('s3env')

CppLibProject(
	s3env, 's3-departures-table', s3env['S3VERSION'], 
    source_files = s3env.Glob ('*.cpp'),
    dependencies = ['s3-messages.cpplib', 's3-env.cpplib', 's3-lex-matcher.cpplib', 's3-geometry.cpplib', 's3-db.cpplib']
)
