Import ('s3env')

CppTestProject(
	s3env, 's3-pt-test', s3env['S3VERSION'],
	source_files = s3env.Glob ('*Test.cpp'),
	# workaround for includes (not needed once merged with 3.2.1)
	include_dir = s3env.SrcDir('#src'),
	dependencies = ['s3-pt.cpplib','s3-security.cpplib']
)
