Import ('testenv')
testmoduleenv = testenv.Copy()

includes = '*.cpp'
excludes = []


testmoduleenv.Append (CPPPATH = [Dir('../../main/map').srcnode().abspath] )
testmoduleenv.Append (LIBPATH = [Dir('../../main/map')] )

testmoduleenv.Append (LIBS = ['map'] )
testmoduleenv.Append (LIBS = ['boost_filesystem'] )

files = testmoduleenv.Glob(includes, excludes)

testmodulename = testmoduleenv.DefaultTestModuleName ()

testprogram = testmoduleenv.Program(testmodulename, files)


testmoduleenv.Test("test.passed", testprogram)

