
/** TimetableResult class header.
	@file TimetableResult.hpp

	This file belongs to the SYNTHESE project (public transportation specialized software)
	Copyright (C) 2002 Hugues Romain - RCS <contact@reseaux-conseil.com>

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/

#ifndef SYNTHESE_timetables_TimetableResult_hpp__
#define SYNTHESE_timetables_TimetableResult_hpp__

#include "TimetableColumn.h"
#include "TimetableWarning.h"

#include <vector>
#include <map>
#include <boost/date_time/time_duration.hpp>

namespace synthese
{
	namespace env
	{
		class CommercialLine;
		class RollingStock;
	}

	namespace timetables
	{
		//////////////////////////////////////////////////////////////////////////
		/// Timetable result generated by TimetableGenerator.
		///	@ingroup m55
		/// @author Hugues Romain
		/// @date 2010
		/// @since 3.1.16
		///
		/// Historically, the content of this class was included in TimetableGenerator.
		class TimetableResult
		{
		public:
			typedef std::vector<TimetableColumn>			Columns;
			typedef std::map<std::size_t, TimetableWarning>		Warnings;
			typedef std::vector<env::CommercialLine*> RowLinesVector;
			typedef std::vector<const TimetableWarning*> RowNotesVector;
			typedef std::vector<const env::RollingStock*> RowRollingStockVector;
			typedef std::vector<boost::posix_time::time_duration> RowTimesVector;
			typedef std::vector<TimetableColumn::tTypeOD>	RowTypeODVector;


		private:
			Columns			_columns;
			Warnings		_warnings;

		public:
			//! @name Getters
			//@{
				const Warnings&	getWarnings()	const { return _warnings; }
				Warnings&	getWarnings()	{ return _warnings; }
				const Columns&	getColumns()	const { return _columns; }
				Columns&	getColumns()	{ return _columns; }
			//@}

			//! @name Services
			//@{
				RowTimesVector			getRowSchedules(std::size_t rank)	const;
				RowLinesVector			getRowLines()								const;
				RowNotesVector			getRowNotes()								const;
				RowRollingStockVector	getRowRollingStock()						const;
				RowTypeODVector			getOriginTypes()							const;
				RowTypeODVector			getDestinationTypes()						const;
			//@}

		};
	}
}

#endif // SYNTHESE_timetables_TimetableResult_hpp__
