Import ('testenv')
testmoduleenv = testenv.ModuleEnv()

includes = '*.cpp'
excludes = []

testmoduleenv.AddModuleDependency ('01_util')
testmoduleenv.Append (LIBS = ['boost_iostreams'] )

files = testmoduleenv.Glob(includes, excludes)

testmodulename = testmoduleenv.DefaultTestModuleName ()

testprogram = testmoduleenv.Program(testmodulename, files)

testmoduleenv.Test("test.passed", testprogram)


