Import ('s3env')

CppLibProject(
	s3env, 's3-framework', s3env['S3VERSION'], 
	source_files = s3env.Glob ('*.cpp'),
	dependencies = [
		'boost.cppinc',
		('boost-iostreams.cpplib',s3env['BOOSTVERSION']),
		('boost-system.cpplib',s3env['BOOSTVERSION']),
		('boost-thread.cpplib',s3env['BOOSTVERSION']), 
		('boost-date-time.cpplib',s3env['BOOSTVERSION']),
		('boost-filesystem.cpplib',s3env['BOOSTVERSION']),
		('boost-regex.cpplib',s3env['BOOSTVERSION']),
		('geos.cpplib','3.2.patch1a'),
		'proj.cpplib'
	],
)

s3env.SubBuild ()


