
Import ('env')

modules = ['36_places_list', '34_departures_table', '33_route_planner', '31_resa', '16_impex', '17_messages', '30_server', '12_security', '32_admin', '13_dblog', '11_interfaces', '15_env', '07_lex_matcher', '14_geography', '06_geometry', '05_html', '04_time', '03_db_ring', '02_db', '01_util__threads', '01_util__iostreams', '01_util', '00_tcp'];

syntheseenv = env.SyntheseEnv (modules)

syntheseenv.SyntheseBuild (syntheseenv.DefaultModuleName ())


