
Import ('mainenv')

modules = ['34_departures_table', '30_server', '15_env', '12_security', '32_admin', '13_dblog', '11_interfaces', '17_messages', '07_lex_matcher', '04_time', '02_db', '01_util', '00_tcp'];


syntheseenv = mainenv.SyntheseEnv (modules)

syntheseenv.SyntheseBuild (syntheseenv.DefaultModuleName ())


