

Import ('mainenv')

modules = ['30_server', '04_time', '02_db', '01_util', '00_tcp'];


syntheseenv = mainenv.SyntheseEnv (modules)


syntheseenv.SyntheseBuild (syntheseenv.DefaultModuleName (), False)
