
/** BarCodeHTMLFormValueInterfaceElement class header.
	@file BarCodeHTMLFormValueInterfaceElement.h

	This file belongs to the SYNTHESE project (public transportation specialized software)
	Copyright (C) 2002 Hugues Romain - RCS <contact@reseaux-conseil.com>

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/

#ifndef SYNTHESE_BarCodeHTMLFormValueInterfaceElement_H__
#define SYNTHESE_BarCodeHTMLFormValueInterfaceElement_H__

#include <boost/shared_ptr.hpp>



namespace synthese
{
	namespace interfaces
	{
		class ValueElementList;
	}
	namespace vinci
	{
		/** BarCodeHTMLFormValueInterfaceElement value interface element class.
			@ingroup m71Values refValues

			Usage :
			@code {{barcodefield}} @endcode
			
			The object parameter of the elements must be actually a const shared_ptr<const AdminInterfaceElement>* object.

			The output is a HTML form able to catch an uid generated by a barcode reader
		*/
		class BarCodeHTMLFormValueInterfaceElement : public interfaces::ValueInterfaceElement
		{
		private:
			
		public:
			/** Evaluates the context and builds the output.
				@param parameters Current execution parameters
				@param variables Current interface variables
				@param object Current displayed object
				@param request Current request
				@return Generated string output
			*/
			std::string getValue(const interfaces::ParametersVector& parameters, interfaces::VariablesMap& variables, const void* object = NULL, const server::Request* request = NULL) const;
			
			/** Parameters storage and quantity verification.
				@param vel Value Elements List : the parameters
				@throw InterfacePageException if the parameters number is incorrect
			*/
			void storeParameters(interfaces::ValueElementList& vel);
		};
	}
}

#endif // SYNTHESE_BarCodeHTMLFormValueInterfaceElement_H__
