import os.path

Import ('mainenv')
moduleenv = mainenv.ModuleEnv()

includes = '*.cpp'
excludes = ['cFichierInterfaces.cpp', 'cFichierSites.cpp', 'cFichierTbDep.cpp', 'cFichierObjetInterfaceStandard.cpp']

moduleenv.AppendMultithreadConf ()

files = moduleenv.Glob(includes, excludes)

moduleenv.StaticLibrary ( moduleenv.DefaultModuleName(), files )



