Import ('s3env')

CppSynthese3LibProject(
	s3env, 's3-analysis', s3env['S3VERSION'],
	source_files = s3env.Glob ('*.cpp'),
	dependencies = [
		's3-pt-website.cpplib',
		's3-pt-journey-planner.cpplib'
	]
)
