
//////////////////////////////////////////////////////////////////////////////////////////
///	VehicleServiceUsagesListService class header.
///	@file VehicleServiceUsagesListService.hpp
///	@author Hugues Romain
///	@date 2014
///
///	This file belongs to the SYNTHESE project (public transportation specialized software)
///	Copyright (C) 2002 Hugues Romain - RCSmobility <contact@rcsmobility.com>
///
///	This program is free software; you can redistribute it and/or
///	modify it under the terms of the GNU General Public License
///	as published by the Free Software Foundation; either version 2
///	of the License, or (at your option) any later version.
///
///	This program is distributed in the hope that it will be useful,
///	but WITHOUT ANY WARRANTY; without even the implied warranty of
///	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
///	GNU General Public License for more details.
///
///	You should have received a copy of the GNU General Public License
///	along with this program; if not, write to the Free Software
///	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

#ifndef SYNTHESE_VehicleServiceUsagesListService_H__
#define SYNTHESE_VehicleServiceUsagesListService_H__

#include "FactorableTemplate.h"
#include "Function.h"

namespace synthese
{
	namespace pt_operation
	{
		class VehicleService;
	}

	namespace analysis
	{
		//////////////////////////////////////////////////////////////////////////
		///	60.15 Function : VehicleServiceUsagesListService.
		/// See https://extranet.rcsmobility.com/projects/synthese/wiki/
		//////////////////////////////////////////////////////////////////////////
		///	@ingroup m60Functions refFunctions
		///	@author Hugues Romain
		///	@date 2014
		/// @since 
		class VehicleServiceUsagesListService:
			public util::FactorableTemplate<server::Function,VehicleServiceUsagesListService>
		{
		public:
			static const std::string PARAMETER_START_DATE;
			static const std::string PARAMETER_END_DATE;
			static const std::string PARAMETER_WITH_DETAIL;

			static const std::string TAG_VEHICLE_SERVICE;
			static const std::string TAG_USAGE;
			
		protected:
			//! \name Page parameters
			//@{
				boost::gregorian::date _startDate;
				boost::gregorian::date _endDate;
				std::vector<boost::shared_ptr<pt_operation::VehicleService> > _services;
				bool _withDetail;
			//@}
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Conversion from attributes to generic parameter maps.
			/// See https://extranet.rcsmobility.com/projects/synthese/wiki/#Request
			//////////////////////////////////////////////////////////////////////////
			///	@return Generated parameters map
			/// @author Hugues Romain
			/// @date 2014
			/// @since 
			util::ParametersMap _getParametersMap() const;
			
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Conversion from generic parameters map to attributes.
			/// See https://extranet.rcsmobility.com/projects/synthese/wiki/#Request
			//////////////////////////////////////////////////////////////////////////
			///	@param map Parameters map to interpret
			/// @author Hugues Romain
			/// @date 2014
			/// @since 
			virtual void _setFromParametersMap(
				const util::ParametersMap& map
			);
			
			
		public:
			VehicleServiceUsagesListService();
			//! @name Setters
			//@{
			//	void setObject(boost::shared_ptr<const Object> value) { _object = value; }
			//@}



			//////////////////////////////////////////////////////////////////////////
			/// Display of the content generated by the function.
			/// @param stream Stream to display the content on.
			/// @param request the current request
			/// @author Hugues Romain
			/// @date 2014
			virtual util::ParametersMap run(std::ostream& stream, const server::Request& request) const;
			
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Gets if the function can be run according to the user of the session.
			/// @param session the current session
			/// @return true if the function can be run
			/// @author Hugues Romain
			/// @date 2014
			virtual bool isAuthorized(const server::Session* session) const;



			//////////////////////////////////////////////////////////////////////////
			/// Gets the Mime type of the content generated by the function.
			/// @return the Mime type of the content generated by the function
			/// @author Hugues Romain
			/// @date 2014
			virtual std::string getOutputMimeType() const;
		};
}	}

#endif // SYNTHESE_VehicleServiceUsagesListService_H__

