
//////////////////////////////////////////////////////////////////////////////////////////
/// HikingTrailSearchFunction class header.
///	@file HikingTrailSearchFunction.h
///	@author Hugues Romain
///	@date 2010
///
///	This file belongs to the SYNTHESE project (public transportation specialized software)
///	Copyright (C) 2002 Hugues Romain - RCSmobility <contact@rcsmobility.com>
///
///	This program is free software; you can redistribute it and/or
///	modify it under the terms of the GNU General Public License
///	as published by the Free Software Foundation; either version 2
///	of the License, or (at your option) any later version.
///
///	This program is distributed in the hope that it will be useful,
///	but WITHOUT ANY WARRANTY; without even the implied warranty of
///	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
///	GNU General Public License for more details.
///
///	You should have received a copy of the GNU General Public License
///	along with this program; if not, write to the Free Software
///	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

#ifndef SYNTHESE_HikingTrailSearchFunction_H__
#define SYNTHESE_HikingTrailSearchFunction_H__

#include "FactorableTemplate.h"
#include "Function.h"

#include <boost/optional.hpp>

namespace synthese
{
	namespace cms
	{
		class Webpage;
	}

	namespace hiking
	{
		//////////////////////////////////////////////////////////////////////////
		///	58.15 Function : Hiking trail search.
		///	@ingroup m58Functions refFunctions
		///	@author Hugues Romain
		///	@date 2010
		/// @since 3.1.16
		//////////////////////////////////////////////////////////////////////////
		/// Two output modes are available :
		///	<ul>
		///		<li>Website page output</li>
		///		<li>XML output</li>
		///	</ul>
		///
		/// <h2>Website page output</h2>
		///
		/// Key : HikingTrailSearchFunction
		///
		/// Parameters :
		///	<ul>
		///		<li>sn : text to search in the name of the trail</li>
		///		<li>pi : id of the page to use to display each item.</li>
		///	</ul>
		///
		/// The page display will be called with the following parameters :
		///	<ul>
		///		<li>roid : id of the trail</li>
		///	</ul>
		///
		/// <h2>XML output</h2>
		///
		/// @todo XML output if the page to use is undefined
		///
		class HikingTrailSearchFunction:
			public util::FactorableTemplate<server::Function,HikingTrailSearchFunction>
		{
		public:
			static const std::string PARAMETER_SEARCH_NAME;
			static const std::string PARAMETER_ITEM_DISPLAY_PAGE_ID;
			static const std::string DATA_HIKING_TRAIL;

		protected:
			//! \name Page parameters
			//@{
				boost::optional<std::string> _searchName;
				boost::shared_ptr<const cms::Webpage> _itemDisplayPage;
			//@}


			//////////////////////////////////////////////////////////////////////////
			/// Conversion from attributes to generic parameter maps.
			///	@return Generated parameters map
			/// @author Hugues Romain
			/// @date 2010
			util::ParametersMap _getParametersMap() const;



			//////////////////////////////////////////////////////////////////////////
			/// Conversion from generic parameters map to attributes.
			///	@param map Parameters map to interpret
			/// @author Hugues Romain
			/// @date 2010
			virtual void _setFromParametersMap(
				const util::ParametersMap& map
			);


		public:
			//! @name Setters
			//@{
			//	void setObject(boost::shared_ptr<const Object> value) { _object = value; }
			//@}



			//////////////////////////////////////////////////////////////////////////
			/// Display of the content generated by the function.
			/// @param stream Stream to display the content on.
			/// @param request the current request
			/// @author Hugues Romain
			/// @date 2010
			virtual util::ParametersMap run(
				std::ostream& stream,
				const server::Request& request
			) const;



			//////////////////////////////////////////////////////////////////////////
			/// Gets if the function can be run according to the user of the session.
			/// @param session the current session
			/// @return true if the function can be run
			/// @author Hugues Romain
			/// @date 2010
			virtual bool isAuthorized(const server::Session* session) const;



			//////////////////////////////////////////////////////////////////////////
			/// Gets the Mime type of the content generated by the function.
			/// @return the Mime type of the content generated by the function
			/// @author Hugues Romain
			/// @date 2010
			virtual std::string getOutputMimeType() const;
		};
	}
}

#endif // SYNTHESE_HikingTrailSearchFunction_H__
