
//////////////////////////////////////////////////////////////////////////////////////////
/// HikingTrailDisplayFunction class header.
///	@file HikingTrailDisplayFunction.h
///	@author Hugues
///	@date 2010
///
///	This file belongs to the SYNTHESE project (public transportation specialized software)
///	Copyright (C) 2002 Hugues Romain - RCSmobility <contact@rcsmobility.com>
///
///	This program is free software; you can redistribute it and/or
///	modify it under the terms of the GNU General Public License
///	as published by the Free Software Foundation; either version 2
///	of the License, or (at your option) any later version.
///
///	This program is distributed in the hope that it will be useful,
///	but WITHOUT ANY WARRANTY; without even the implied warranty of
///	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
///	GNU General Public License for more details.
///
///	You should have received a copy of the GNU General Public License
///	along with this program; if not, write to the Free Software
///	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

#ifndef SYNTHESE_HikingTrailDisplayFunction_H__
#define SYNTHESE_HikingTrailDisplayFunction_H__

#include "FactorableTemplate.h"
#include "FunctionWithSite.h"

namespace synthese
{
	namespace hiking
	{
		class HikingTrail;

		//////////////////////////////////////////////////////////////////////////
		/// 58.15 Function : hiking trail value display.
		///	@author Hugues Romain
		///	@date 2010
		///	@ingroup m58Functions refFunctions
		//////////////////////////////////////////////////////////////////////////
		/// Key : HikingTrailDisplayFunction
		///
		/// Parameters :
		///	<ul>
		///		<li>roid : ID of the trail to extract the data from</li>
		///		<li>key : Data to extract :</li>
		///		<ul>
		///			<li>name : name of the trail</li>
		///			<li>duration : duration of the trail</li>
		///			<li>profile : profile of the trail</li>
		///			<li>url : url of link to the trail home page</li>
		///		</ul>
		///	</ul>
		class HikingTrailDisplayFunction:
			public util::FactorableTemplate<cms::FunctionWithSite<true>, HikingTrailDisplayFunction>
		{
		public:
			static const std::string PARAMETER_KEY;

		protected:
			//! \name Page parameters
			//@{
				boost::shared_ptr<const HikingTrail> _hikingTrail;
				std::string _key;
			//@}


			//////////////////////////////////////////////////////////////////////////
			/// Conversion from attributes to generic parameter maps.
			///	@return Generated parameters map
			/// @author Hugues
			/// @date 2010
			util::ParametersMap _getParametersMap() const;



			//////////////////////////////////////////////////////////////////////////
			/// Conversion from generic parameters map to attributes.
			///	@param map Parameters map to interpret
			/// @author Hugues
			/// @date 2010
			virtual void _setFromParametersMap(
				const util::ParametersMap& map
			);


		public:


			//////////////////////////////////////////////////////////////////////////
			/// Display of the content generated by the function.
			/// @param stream Stream to display the content on.
			/// @param request the current request
			/// @author Hugues
			/// @date 2010
			virtual util::ParametersMap run(
				std::ostream& stream,
				const server::Request& request
			) const;



			//////////////////////////////////////////////////////////////////////////
			/// Gets if the function can be run according to the user of the session.
			/// @param session the current session
			/// @return true if the function can be run
			/// @author Hugues
			/// @date 2010
			virtual bool isAuthorized(const server::Session* session) const;



			//////////////////////////////////////////////////////////////////////////
			/// Gets the Mime type of the content generated by the function.
			/// @return the Mime type of the content generated by the function
			/// @author Hugues
			/// @date 2010
			virtual std::string getOutputMimeType() const;
		};
	}
}

#endif // SYNTHESE_HikingTrailDisplayFunction_H__
