Import ('s3env')

senv = s3env.Clone ()

if s3env.GetPlatform () == 'posix':
   CppLibProject (senv, 's3-agi-client', s3env['S3VERSION'],
                        source_files = senv.Glob ('*.c'),
                        dependencies = [])
