Import ('testenv')
testmoduleenv = testenv.ModuleEnv()

includes = '*.cpp'
excludes = []

testmoduleenv.AddModuleDependency ('04_time')

files = testmoduleenv.Glob(includes, excludes)

testmodulename = testmoduleenv.DefaultTestModuleName ()

testprogram = testmoduleenv.Program(testmodulename, files)

testmoduleenv.Test("test.passed", testprogram)

