Import ('testenv')
testmoduleenv = testenv.TestModuleEnv (includes='*.cpp', 
                                       excludes=[], 
                                       modules=['04_time'], 
                                       boostlibs=[], 
                                       withSQLite=False, 
                                       withMultithreading=True)



