//////////////////////////////////////////////////////////////////////////////////////////
///	AlertListService class header.
///	@file AlertListService.hpp
///	@author Marc Jambert
///	@date 2014
///
///	This file belongs to the SYNTHESE project (public transportation specialized software)
///	Copyright (C) 2002 Hugues Romain - RCSmobility <contact@rcsmobility.com>
///
///	This program is free software; you can redistribute it and/or
///	modify it under the terms of the GNU General Public License
///	as published by the Free Software Foundation; either version 2
///	of the License, or (at your option) any later version.
///
///	This program is distributed in the hope that it will be useful,
///	but WITHOUT ANY WARRANTY; without even the implied warranty of
///	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
///	GNU General Public License for more details.
///
///	You should have received a copy of the GNU General Public License
///	along with this program; if not, write to the Free Software
///	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

#ifndef SYNTHESE_AlertListService_H__
#define SYNTHESE_AlertListService_H__

#include "FactorableTemplate.h"
#include "Function.h"

namespace synthese
{
	namespace util
	{
		class Registrable;
	}

	namespace db
	{

		//////////////////////////////////////////////////////////////////////////
		///	62.15 Function : AlertListService.
		//////////////////////////////////////////////////////////////////////////
		///	@ingroup m10Functions refFunctions
		///	@author mjambert
		///	@date 2014
		/// @since 3.5.0
		class AlertListService:
			public util::FactorableTemplate<server::Function,AlertListService>
		{
		public:
			static const std::string PARAMETER_ADDITIONAL_PARAMETERS;
			static const std::string DATA_OBJECT;
			
		protected:
			//! \name Page parameters
			//@{
				boost::shared_ptr<const util::Registrable> _object;
				bool _additionalParameters;
			//@}
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Conversion from attributes to generic parameter maps.
			/// See https://extranet.rcsmobility.com/projects/synthese/wiki/Object_view#Request
			//////////////////////////////////////////////////////////////////////////
			///	@return Generated parameters map
			/// @author mjambert
			/// @date 2014
			/// @since 3.5.0
			util::ParametersMap _getParametersMap() const;
			
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Conversion from generic parameters map to attributes.
			/// See https://extranet.rcsmobility.com/projects/synthese/wiki/Object_view#Request
			//////////////////////////////////////////////////////////////////////////
			///	@param map Parameters map to interpret
			/// @author mjambert
			/// @date 2014
			/// @since 3.5.0
			virtual void _setFromParametersMap(
				const util::ParametersMap& map
			);
			
			
		public:
			AlertListService();



			//////////////////////////////////////////////////////////////////////////
			/// Display of the content generated by the function.
			/// @param stream Stream to display the content on.
			/// @param request the current request
			/// @author mjambert
			/// @date 2014
			virtual util::ParametersMap run(std::ostream& stream, const server::Request& request) const;
			
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Gets if the function can be run according to the user of the session.
			/// @param session the current session
			/// @return true if the function can be run
			/// @author mjambert
			/// @date 2014
			virtual bool isAuthorized(const server::Session* session) const;



			//////////////////////////////////////////////////////////////////////////
			/// Gets the Mime type of the content generated by the function.
			/// @return the Mime type of the content generated by the function
			/// @author mjambert
			/// @date 2014
			virtual std::string getOutputMimeType() const;
		};
}	}

#endif // SYNTHESE_AlertListService_H__

