Import ('s3env')

CppSynthese3LibProject(
	s3env, 's3-openstreetmap', s3env['S3VERSION'],
    source_files = s3env.Glob ('*.cpp'),
	dependencies = ['boost.cppinc', 's3-util.cpplib', 'proj.cpplib', 's3-road.cpplib', 'expat.cpplib'],
)
