import os.path

Import ('mainenv')
moduleenv = mainenv.ModuleEnv()

includes = '*.cpp'
excludes = ['cFichierSites.cpp', 'cFichierTbDep.cpp']

moduleenv.AppendMultithreadConf ()

files = moduleenv.Glob(includes, excludes)

moduleenv.StaticLibrary ( moduleenv.DefaultModuleName(), files )



