import os.path

Import ('mainenv')
moduleenv = mainenv.ModuleEnv()

includes = '*.cpp'
excludes = []

moduleenv.AppendMultithreadConf ()


files = moduleenv.Glob(includes, excludes)


if (moduleenv['PLATFORM'] == 'win32'):
	# Does not compile under posix at the moment !
	moduleenv.Program(moduleenv.DefaultModuleName (), files)
