Import ('s3env')

senv = s3env.Clone ()

prj = CppLibProject (senv, 's3-db-ring', s3env['S3VERSION'], 
                     source_files = senv.Glob ('*.cpp'),
                     dependencies = ['s3-db.shlib', 's3-util-iostreams.shlib'])
senv.SConsProject (prj)
