@REM This script have to be run in the directory of the SQLite database file
@echo off
echo Removing dates...
sqlite3 C:\forge\devel\synthese3\build\win32\vc-8_0\Debug\main\programs\synthese_sai\config.db3 "DELETE FROM t005_service_dates WHERE date > date('now','+1 day');"
echo Removing useless services...
sqlite3 C:\forge\devel\synthese3\build\win32\vc-8_0\Debug\main\programs\synthese_sai\config.db3 "DELETE FROM t016_scheduled_services WHERE NOT EXISTS (SELECT id FROM t005_service_dates WHERE t005_service_dates.service_id = t016_scheduled_services.id);"
sqlite3 C:\forge\devel\synthese3\build\win32\vc-8_0\Debug\main\programs\synthese_sai\config.db3 "DELETE FROM t017_continuous_services WHERE NOT EXISTS (SELECT id FROM t005_service_dates WHERE t005_service_dates.service_id = t017_continuous_services.id);"
echo Removing useless routes...
sqlite3 C:\forge\devel\synthese3\build\win32\vc-8_0\Debug\main\programs\synthese_sai\config.db3 "DELETE FROM t009_lines WHERE NOT EXISTS (SELECT id FROM t017_continuous_services WHERE t017_continuous_services.path_id=t009_lines.id) AND NOT EXISTS (SELECT id FROM t016_scheduled_services WHERE t016_scheduled_services.path_id=t009_lines.id);"
echo Removing Useless linestops...
sqlite3 C:\forge\devel\synthese3\build\win32\vc-8_0\Debug\main\programs\synthese_sai\config.db3 "DELETE FROM t010_line_stops WHERE NOT EXISTS (SELECT id FROM t009_lines WHERE t010_line_stops.line_id = t009_lines.id);"
echo Vacuum...
sqlite3 C:\forge\devel\synthese3\build\win32\vc-8_0\Debug\main\programs\synthese_sai\config.db3 "VACUUM;"
pause
