import os.path

Import ('mainenv')
moduleenv = mainenv.Copy()

includes = '*.cpp'
excludes = []

moduleenv.Append (CPPPATH = [Dir('..').srcnode().abspath] )

moduleenv.AppendMultithreadConf ()

files = moduleenv.Glob(includes, excludes)

moduleenv.Append ( LIBS = ['boost_filesystem'] )  

moduleenv.StaticLibrary ( moduleenv.DefaultModuleName(), files )


