Import ('s3env')

senv = s3env.Clone ()

prj = CppLibProject (senv, 's3-geography', s3env['S3VERSION'], 
                     source_files = senv.Glob ('*.cpp'),
                     dependencies = ['s3-geometry.shlib'])
senv.SConsProject (prj)

