function package_add_click()
{
 $('#package_add_modal').modal('show');
 return false;
}

function package_remove_click()
{
 $('#package_remove_modal').modal('show');
 return false;
}

function object_add_click()
{
  $('#object_add_id_field').val('');
  $('#object_add_check_div').html('');
  $('#object_add_modal').modal('show');
  return false;
}

function object_add_check_div_update()
{
 var id = $('#object_add_id_field').val();
 if(id)
 {
  $.get(
   '/connect/ajax/get_object_informations?roid='+ id,
   function(data) {
     $('#object_add_check_div').html(data);
   }
  );
 }
 else
 {
   $('#object_add_check_div').html('');
 }
}

function object_add_confirm_click()
{
  add_object({
    id: $('#object_add_id_field').val(),
    name: $('#object_add_check_name').html(),
    table: $('#object_add_check_table').html()
  });
  $('#object_add_modal').modal('hide');
}

function object_remove_click()
{
  object_remove_tr = $(this).closest('tr'); 
  var object_name = object_remove_tr.find('td').first().html();
  $('#object_remove_name_span').html(object_name);
  $('#object_remove_modal').modal('show');
  return false;
}

function object_remove_confirm_click()
{
  $('#object_remove_modal').modal('hide');
  object_remove_tr.remove();
  return false;
}

function add_object(object)
{
 var link_name = 'remove_'+ object.id +'_link';
 $('#objects_table').find('tbody').append(
   '<tr data-id="'+ object.id +'">'+
   '<td>'+ object.name +'</td>'+
   '<td>'+ object.table +'</td>'+
   (edit ? '<td><div class="pull-right" id="'+ link_name +'"><a href="#"><i class="icon-remove"></i></a></div></td>': '')+
   '</tr>'
 );
 $('#'+ link_name).click(object_remove_click);
}

function update_form_check()
{
  var object_id_val = '';
  $('#objects_table').find('tbody').find('tr').each(function(){
    if(object_id_val) object_id_val += ',';
    object_id_val += $(this).attr('data-id');
  });
  $('#update_actionParam_field_object_ids_AUTOGENERATEDFIELDID').val(object_id_val);
  return true;
}

function display()
{
  for(var i=0; i<objects.length; ++i)
  {
    add_object(objects[i]);
  }
}

$(function(){
 $('#package_add_link').click(package_add_click);
 $('#package_add_link').tooltip({placement:'right'});
 $('#package_remove_link').click(package_remove_click);
 $('#package_remove_link').tooltip({placement:'right'});
 $('#object_add_link').click(object_add_click);
 $('#object_add_id_field').on('keyup', object_add_check_div_update);
 $('#object_add_confirm_link').click(object_add_confirm_click);
 $('#update_form').submit(update_form_check);
 $('#object_remove_confirm_link').click(object_remove_confirm_click);
 display();
});