import os.path

Import ('mainenv')
moduleenv = mainenv.Copy()

includes = '*.cpp'
excludes = ['cServeurMnesia.cpp', 'cIndicateurs.cpp', 'cAccesPADe.cpp' ]

moduleenv.Append (CPPPATH = [Dir('..').srcnode().abspath] )

moduleenv.AppendMultithreadConf ()

if (moduleenv['PLATFORM'] != 'win32'):
  excludes.append ('stdafx.cpp')


moduleenv.Append ( LIBPATH = ['../map'] )  
moduleenv.Append ( LIBPATH = ['../tcp'] )  
moduleenv.Append ( LIBS = ['map'] )  
moduleenv.Append ( LIBS = ['tcp'] )  
moduleenv.Append ( LIBS = ['boost_filesystem'] )  



files = moduleenv.Glob(includes, excludes)



moduleenv.Program(moduleenv.DefaultModuleName (), files)
