import os.path

Import ('mainenv')
moduleenv = mainenv.Copy()

includes = '*.cpp'
excludes = []

moduleenv.Append (CPPPATH = [Dir('..').srcnode().abspath] )

if (moduleenv['PLATFORM'] == 'posix'):
  moduleenv.Append (CCFLAGS= '-pthread' )
  moduleenv.Append (LIBS= ['pthread'] ) 

elif (moduleenv['PLATFORM'] == 'win32'):
  moduleenv.Append ( LIBS = ['ws2_32.lib'] )  


moduleenv.Append ( LIBPATH = ['../tcp'] )  
moduleenv.Append ( LIBS = ['tcp'] )  


files = moduleenv.Glob(includes, excludes)



moduleenv.Program(moduleenv.DefaultModuleName (), files)
