import os.path

Import ('mainenv')
moduleenv = mainenv.ModuleEnv()

includes = '*.cpp'
excludes = []


files = moduleenv.Glob(includes, excludes)
moduleenv.AppendMultithreadConf ()

moduleenv.StaticLibrary ( moduleenv.DefaultModuleName(), files )



