/** NotificationEventsService class header.
	@file NotificationEventsService.hpp
	@author yves.martin
	@date 2015

	This file belongs to the SYNTHESE project (public transportation specialized software)
	Copyright (C) 2015 Hugues Romain - RCSmobility <contact@rcsmobility.com>

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/

#ifndef SYNTHESE_NotificationEventsService_hpp__
#define SYNTHESE_NotificationEventsService_hpp__

#include <FactorableTemplate.h>
#include <Function.h>
#include <ParametersMap.h>

#include <string>

namespace synthese
{
	namespace server
	{
		class Request;
		class Session;
	} /* namespace server */

	namespace messages
	{
		class Scenario;		// Forward declaration

		/**
			17.15 Function : NotificationEventsService.
			TODO See https://projects.open-transport.org/projects/terminus/wiki/NotificationProviders
			@ingroup m17Functions refFunctions
			@author yves.martin
			@date 2015

			This "notification_events" service provides counts of
			- events in retry process or failed
			- events in HOLD status
			- unhold events, moving corresponding events from HOLD to READY status

			Processing is done on all events related to all alarm messages in a scenario
		*/
		class NotificationEventsService:
			public util::FactorableTemplate<server::Function, NotificationEventsService>

		{
		public:
			/// Scenario ID
			static const std::string PARAMETER_SCENARIO_ID;

			/// Service option to free hold events
			static const std::string PARAMETER_UNHOLD_EVENTS;

			/// Tag holding number of hold events
			static const std::string TAG_HOLD_COUNT;

			/// Tag holding number of hold events
			static const std::string TAG_FAILED_COUNT;

		private:
			const Scenario* _scenario;
			bool _optionUnhold;

		protected:
			//////////////////////////////////////////////////////////////////////////
			/// Generates a generic parameters map from the Service parameters.
			/// @return The generated parameters map
			util::ParametersMap _getParametersMap() const;

			//////////////////////////////////////////////////////////////////////////
			/// Reads the parameters of the Service on a generic parameters map.
			/// @param map Parameters map to interpret
			/// @exception ServiceException Occurs when some parameters are missing or incorrect.
			void _setFromParametersMap(const util::ParametersMap& map);

		public:
			NotificationEventsService();
			virtual ~NotificationEventsService() { };

			//////////////////////////////////////////////////////////////////////////
			/// Display of the content generated by the function.
			/// @param stream Stream to display the content on.
			/// @param request the current request
			/// @author yves.martin
			/// @date 2015
			virtual util::ParametersMap run(std::ostream& stream, const server::Request& request) const;

			//////////////////////////////////////////////////////////////////////////
			/// Gets if the function can be run according to the user of the session.
			/// @param session the current session
			/// @return true if the function can be run
			/// @author yves.martin
			/// @date 2015
			virtual bool isAuthorized(const server::Session* session) const;

			//////////////////////////////////////////////////////////////////////////
			/// Gets the Mime type of the content generated by the function.
			/// @return the Mime type of the content generated by the function
			/// @author yves.martin
			/// @date 2015
			virtual std::string getOutputMimeType() const;
		};

	} /* namespace messages */
} /* namespace synthese */

#endif /* SYNTHESE_NotificationEventsService_hpp__ */
