
//////////////////////////////////////////////////////////////////////////////////////////
/// ScenariosListFunction class header.
///	@file ScenariosListFunction.hpp
///	@author Hugues Romain
///	@date 2010
///
///	This file belongs to the SYNTHESE project (public transportation specialized software)
///	Copyright (C) 2002 Hugues Romain - RCSmobility <contact@rcsmobility.com>
///
///	This program is free software; you can redistribute it and/or
///	modify it under the terms of the GNU General Public License
///	as published by the Free Software Foundation; either version 2
///	of the License, or (at your option) any later version.
///
///	This program is distributed in the hope that it will be useful,
///	but WITHOUT ANY WARRANTY; without even the implied warranty of
///	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
///	GNU General Public License for more details.
///
///	You should have received a copy of the GNU General Public License
///	along with this program; if not, write to the Free Software
///	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

#ifndef SYNTHESE_ScenariosListFunction_H__
#define SYNTHESE_ScenariosListFunction_H__

#include "FactorableTemplate.h"
#include "Function.h"

#include <boost/logic/tribool.hpp>

namespace synthese
{
	namespace cms
	{
		class Webpage;
	}

	namespace messages
	{
		class MessagesSection;
		class ScenarioFolder;
		class SentScenario;
		class ScenarioTemplate;

		//////////////////////////////////////////////////////////////////////////
		///	17.15 Function : ScenariosListFunction.
		/// See https://extranet.rcsmobility.com/projects/synthese/wiki/Scenarii_list
		//////////////////////////////////////////////////////////////////////////
		///	@ingroup m17Functions refFunctions
		///	@author Hugues Romain
		///	@date 2010
		/// @since 3.2.0
		class ScenariosListFunction:
			public util::FactorableTemplate<server::Function,ScenariosListFunction>
		{
		public:
			static const std::string PARAMETER_SHOW_TEMPLATES;
			static const std::string PARAMETER_FOLDER_ID;
			static const std::string PARAMETER_CMS_TEMPLATE_ID;
			static const std::string PARAMETER_CURRENTLY_DISPLAYED;
			static const std::string PARAMETER_SECTION_IN;
			static const std::string PARAMETER_SECTION_OUT;
			static const std::string PARAMETER_TEXT_SEARCH;
			static const std::string PARAMETER_ARCHIVES;

			static const std::string TAG_SCENARIO;

		protected:
			//! \name Page parameters
			//@{
				bool _showTemplates;
				boost::optional<bool> _showCurrentlyDisplayed;
				boost::shared_ptr<const ScenarioFolder> _parentFolder;
				boost::shared_ptr<const cms::Webpage> _cmsTemplate;
				boost::optional<MessagesSection&> _sectionIn;
				boost::optional<MessagesSection&> _sectionOut;
				boost::optional<std::string> _textSearch;
				boost::optional<bool> _archivesOnly;
			//@}


			//////////////////////////////////////////////////////////////////////////
			/// Conversion from attributes to generic parameter maps.
			/// See https://extranet.rcsmobility.com/projects/synthese/wiki/Scenarii_list#Request
			//////////////////////////////////////////////////////////////////////////
			///	@return Generated parameters map
			/// @author Hugues Romain
			/// @date 2010
			util::ParametersMap _getParametersMap() const;



			//////////////////////////////////////////////////////////////////////////
			/// Conversion from generic parameters map to attributes.
			/// See https://extranet.rcsmobility.com/projects/synthese/wiki/Scenarii_list#Request
			//////////////////////////////////////////////////////////////////////////
			///	@param map Parameters map to interpret
			/// @author Hugues Romain
			/// @date 2010
			virtual void _setFromParametersMap(
				const util::ParametersMap& map
			);


		public:
			ScenariosListFunction();



			//////////////////////////////////////////////////////////////////////////
			/// Display of the content generated by the function.
			/// @param stream Stream to display the content on.
			/// @param request the current request
			/// @author Hugues Romain
			/// @date 2010
			virtual util::ParametersMap run(
				std::ostream& stream,
				const server::Request& request
			) const;



			//////////////////////////////////////////////////////////////////////////
			/// Gets if the function can be run according to the user of the session.
			/// @param session the current session
			/// @return true if the function can be run
			/// @author Hugues Romain
			/// @date 2010
			virtual bool isAuthorized(const server::Session* session) const;



			//////////////////////////////////////////////////////////////////////////
			/// Gets the Mime type of the content generated by the function.
			/// @return the Mime type of the content generated by the function
			/// @author Hugues Romain
			/// @date 2010
			virtual std::string getOutputMimeType() const;
		};
	}
}

#endif // SYNTHESE_ScenariosListFunction_H__
