Import ('env')

## SHAPELIB ##########################################################################################################################
## http://shapelib.maptools.org/

#if env.GetPlatform () == 'win32':
#   senv['MAKEDEFSYMBOLPATTERN'] = '_(sqlite3_[^ ]*)'

files = ['src/shpopen.c', 'src/dbfopen.c', 'src/safileio.c']

CppLibProject(
	env
	, 'shapelib'
	, '1.3.0a2'
	, source_files = files
	, include_dir = env.SrcDir('src')
	, filesrootdir = env.SrcDir('src')
)
files = ['src/shptest.c']
CppBinProject(
	env
	, 'shapetest'
	, '3.4.2'
	, source_files = files
	, include_dir = env.SrcDir('src')
	, dependencies = ['shapelib.cpplib']
	, filesrootdir = env.SrcDir('src')
)

