Import ('s3env')

CppLibProject(
	s3env, 's3-map', s3env['S3VERSION'], 
    source_files = s3env.Glob ('*.cpp'),
	dependencies = ['s3-util.cpplib', 's3-geometry.cpplib', 's3-env.cpplib', 'boost.cppinc', 'boost-system.cpplib'],
)
