Import ('s3env')

senv = s3env.Clone ()

#prj = CppLibProject (senv, 's3-map', s3env['S3VERSION'], 
#                     source_files = senv.Glob ('*.cpp'),
#                     dependencies = [])
#senv.SConsProject (prj)

