
//////////////////////////////////////////////////////////////////////////////////////////
/// PlacesListRequestFunction class header.
///	@file PlacesListRequestFunction.hpp
///	@author Hugues Romain
///	@date 2010
///
///	This file belongs to the SYNTHESE project (public transportation specialized software)
///	Copyright (C) 2002 Hugues Romain - RCS <contact@reseaux-conseil.com>
///
///	This program is free software; you can redistribute it and/or
///	modify it under the terms of the GNU General Public License
///	as published by the Free Software Foundation; either version 2
///	of the License, or (at your option) any later version.
///
///	This program is distributed in the hope that it will be useful,
///	but WITHOUT ANY WARRANTY; without even the implied warranty of
///	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
///	GNU General Public License for more details.
///
///	You should have received a copy of the GNU General Public License
///	along with this program; if not, write to the Free Software
///	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

#ifndef SYNTHESE_PlacesListRequestFunction_H__
#define SYNTHESE_PlacesListRequestFunction_H__

#include "FactorableTemplate.h"
#include "Function.h"

namespace synthese
{
	namespace pt_website
	{
		//////////////////////////////////////////////////////////////////////////
		///	56.15 Function : PlacesListRequestFunction.
		///	@ingroup m56Functions refFunctions
		///	@author Hugues Romain
		///	@date 2010
		/// @since 3.1.16
		//////////////////////////////////////////////////////////////////////////
		/// Key : places_list_request
		///
		/// Parameters :
		///	<ul>
		///		<li>text _field: Text field (can be a string with script code)</li>
		///		<li>city_text_field : City text field (can be a string with script code)</li>
		///		<li>for_departure : 1|0 : 1 = departures city list, 0 = arrival city list</li>
		///		<li>number : Number of answers to return</li>
		///	</ul>
		class PlacesListRequestFunction:
			public util::FactorableTemplate<server::Function,PlacesListRequestFunction>
		{
		public:
			static const std::string PARAMETER_TEXT_FIELD;
			static const std::string PARAMETER_CITY_TEXT_FIELD;
			static const std::string PARAMETER_FOR_DEPARTURE;
			static const std::string PARAMETER_NUMBER;

		protected:
			//! \name Page parameters
			//@{
				std::string _textField;
				std::string _cityTextField;
				bool _forDeparture;
				std::size_t _number;
			//@}
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Conversion from attributes to generic parameter maps.
			///	@return Generated parameters map
			/// @author Hugues Romain
			/// @date 2010
			server::ParametersMap _getParametersMap() const;
			
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Conversion from generic parameters map to attributes.
			///	@param map Parameters map to interpret
			/// @author Hugues Romain
			/// @date 2010
			virtual void _setFromParametersMap(
				const server::ParametersMap& map
			);
			
			
		public:
			//! @name Setters
			//@{
			//	void setObject(boost::shared_ptr<const Object> value) { _object = value; }
			//@}



			//////////////////////////////////////////////////////////////////////////
			/// Display of the content generated by the function.
			/// @param stream Stream to display the content on.
			/// @param request the current request
			/// @author Hugues Romain
			/// @date 2010
			virtual void run(std::ostream& stream, const server::Request& request) const;
			
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Gets if the function can be run according to the user of the session.
			/// @param session the current session
			/// @return true if the function can be run
			/// @author Hugues Romain
			/// @date 2010
			virtual bool isAuthorized(const server::Session* session) const;



			//////////////////////////////////////////////////////////////////////////
			/// Gets the Mime type of the content generated by the function.
			/// @return the Mime type of the content generated by the function
			/// @author Hugues Romain
			/// @date 2010
			virtual std::string getOutputMimeType() const;
		};
	}
}

#endif // SYNTHESE_PlacesListRequestFunction_H__
