
//////////////////////////////////////////////////////////////////////////////////////////
/// ServiceInformationsFunction class header.
///	@file ServiceInformationsFunction.hpp
///	@author Hugues Romain
///	@date 2010
///
///	This file belongs to the SYNTHESE project (public transportation specialized software)
///	Copyright (C) 2002 Hugues Romain - RCSmobility <contact@rcsmobility.com>
///
///	This program is free software; you can redistribute it and/or
///	modify it under the terms of the GNU General Public License
///	as published by the Free Software Foundation; either version 2
///	of the License, or (at your option) any later version.
///
///	This program is distributed in the hope that it will be useful,
///	but WITHOUT ANY WARRANTY; without even the implied warranty of
///	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
///	GNU General Public License for more details.
///
///	You should have received a copy of the GNU General Public License
///	along with this program; if not, write to the Free Software
///	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

#ifndef SYNTHESE_ServiceInformationsFunction_H__
#define SYNTHESE_ServiceInformationsFunction_H__

#include "FactorableTemplate.h"
#include "Function.h"

namespace synthese
{
	namespace graph
	{
		class ServicePointer;
	}

	namespace cms
	{
		class Webpage;
	}

	namespace pt
	{
		class ScheduledService;
	}

	namespace pt_website
	{
		//////////////////////////////////////////////////////////////////////////
		///	56.15 Function : ServiceInformationsFunction.
		///	@ingroup m56Functions refFunctions
		///	@author Hugues Romain
		///	@date 2010
		/// @since 3.2.0
		//////////////////////////////////////////////////////////////////////////
		/// Key : ServiceInformationsFunction
		///
		/// Parameters :
		///	<ul>
		///		<li>roid : id of the service to display</li>
		///	</ul>
		class ServiceInformationsFunction:
			public util::FactorableTemplate<server::Function,ServiceInformationsFunction>
		{
		public:
			static const std::string PARAMETER_STOP_PAGE_ID;
			static const std::string PARAMETER_DATE;

		protected:
			//! \name Page parameters
			//@{
				boost::shared_ptr<const pt::ScheduledService> _service;
				boost::shared_ptr<const cms::Webpage> _stopPage;
				boost::posix_time::ptime _date;
			//@}


			//////////////////////////////////////////////////////////////////////////
			/// Conversion from attributes to generic parameter maps.
			///	@return Generated parameters map
			/// @author Hugues Romain
			/// @date 2010
			util::ParametersMap _getParametersMap() const;



			//////////////////////////////////////////////////////////////////////////
			/// Conversion from generic parameters map to attributes.
			///	@param map Parameters map to interpret
			/// @author Hugues Romain
			/// @date 2010
			virtual void _setFromParametersMap(
				const util::ParametersMap& map
			);

			static const std::string PAGE_PARAMETER_RANK;
			static const std::string PAGE_PARAMETER_TIME;
			static const std::string PAGE_PARAMETER_DURATION;
			static const std::string PAGE_PARAMETER_STOP_POINT_ID;
			static const std::string PAGE_PARAMETER_STOP_AREA_ID;

			void _displayStop(
				std::ostream& stream,
				bool departureTime,
				const graph::ServicePointer& ptr,
				const server::Request& request
			) const;

			void _displaySIRI(std::ostream& stream) const;

		public:
			ServiceInformationsFunction();

			//! @name Setters
			//@{
				void setService(boost::shared_ptr<const pt::ScheduledService> value) { _service = value; }
			//@}



			//////////////////////////////////////////////////////////////////////////
			/// Display of the content generated by the function.
			/// @param stream Stream to display the content on.
			/// @param request the current request
			/// @author Hugues Romain
			/// @date 2010
			virtual util::ParametersMap run(std::ostream& stream, const server::Request& request) const;



			//////////////////////////////////////////////////////////////////////////
			/// Gets if the function can be run according to the user of the session.
			/// @param session the current session
			/// @return true if the function can be run
			/// @author Hugues Romain
			/// @date 2010
			virtual bool isAuthorized(const server::Session* session) const;



			//////////////////////////////////////////////////////////////////////////
			/// Gets the Mime type of the content generated by the function.
			/// @return the Mime type of the content generated by the function
			/// @author Hugues Romain
			/// @date 2010
			virtual std::string getOutputMimeType() const;
		};
	}
}

#endif // SYNTHESE_ServiceInformationsFunction_H__
