
Import ('env')

modules = ['30_server', '08_acapela_client', '09_agi_client', '04_time', '01_util__threads', '01_util__iostreams', '01_util', '00_tcp'];

syntheseenv = env.SyntheseEnv (modules)
syntheseenv.AddDependency ('nscube')


syntheseenv.SyntheseProgram (syntheseenv.DefaultModuleName (), generatemain = False, includes = '*.cpp')


