Import ('s3env')

CppSynthese3LibProject(
	s3env, 's3-resa', s3env['S3VERSION'], 
	source_files = s3env.Glob ('*.cpp'),
	dependencies = ['s3-places-list.cpplib', 's3-route-planner.cpplib', 's3-env.cpplib']
)
