Import ('s3env')

senv = s3env.Clone ()

CppTestProject (senv, 's3-db-ring-test', s3env['S3VERSION'], source_files = senv.Glob ('*Test.cpp'),
                     dependencies = ['s3-db-ring.cpplib'])
