Import ('s3env')

senv = s3env.Clone ()

prj = CppTestProject (senv, 's3-db-test', s3env['S3VERSION'], source_files = senv.Glob ('*Test.cpp'),
                     dependencies = ['s3-db.shlib'])
senv.SConsProject (prj)
