import os.path

Import ('mainenv')
moduleenv = mainenv.ModuleEnv()

includes = '*.cpp'
excludes = ['cServeurMnesia.cpp']


moduleenv.AppendMultithreadConf ()

if (moduleenv['PLATFORM'] != 'win32'):
  excludes.append ('stdafx.cpp')


moduleenv.AddModuleDependency ('map');
moduleenv.AddModuleDependency ('00_tcp');
moduleenv.AddModuleDependency ('01_util');
moduleenv.AddModuleDependency ('04_time');
moduleenv.AddModuleDependency ('70_server');

moduleenv.Append ( LIBS = ['boost_filesystem'] )  


files = moduleenv.Glob(includes, excludes)



moduleenv.Program(moduleenv.DefaultModuleName (), files)
