import os.path

Import ('mainenv')
moduleenv = mainenv.Copy()

includes = '*.cpp'
excludes = ['cServeurMnesia.cpp']

moduleenv.Append (CPPPATH = [Dir('..').srcnode().abspath] )

moduleenv.AppendMultithreadConf ()

if (moduleenv['PLATFORM'] != 'win32'):
  excludes.append ('stdafx.cpp')


moduleenv.Append ( LIBPATH = ['../map'] )  
moduleenv.Append ( LIBPATH = ['../00_tcp'] )  
moduleenv.Append ( LIBPATH = ['../04_time'] )  
moduleenv.Append ( LIBS = ['map'] )  
moduleenv.Append ( LIBS = ['00_tcp'] )  
moduleenv.Append ( LIBS = ['04_time'] )  
moduleenv.Append ( LIBS = ['boost_filesystem'] )  



files = moduleenv.Glob(includes, excludes)



moduleenv.Program(moduleenv.DefaultModuleName (), files)
