Import ('s3env')

senv = s3env.Clone ()

prj = CppTestProject (senv, 's3-lex-matcher-test', s3env['S3VERSION'], source_files = senv.Glob ('*Test.cpp'),
                     dependencies = ['s3-lex-matcher.shlib'])
senv.SConsProject (prj)


