Import ('env')

## BZIP2 ##########################################################################################################################
## http://bzip.org/

senv = env.Clone()

senv.Append ( CPPDEFINES = ['_LIB'] )

CppLibProject(
	senv
	, 'bzip2'
	, '1.0.6'
	, source_files = senv.Glob ('*.c', ['unzcrash.c','bzip2.c','spewG.c','bzip2recover.c','dlltest.c'], dir=senv.SrcDir('src'), prefix='src/')
	, include_dir = senv.SrcDir('src')
	, filesrootdir = senv.SrcDir('src')
)

