
//////////////////////////////////////////////////////////////////////////////////////////
///	InterSYNTHESEPackageGetContentService class header.
///	@file InterSYNTHESEPackageGetContentService.hpp
///	@author hromain
///	@date 2013
///
///	This file belongs to the SYNTHESE project (public transportation specialized software)
///	Copyright (C) 2002 Hugues Romain - RCSmobility <contact@rcsmobility.com>
///
///	This program is free software; you can redistribute it and/or
///	modify it under the terms of the GNU General Public License
///	as published by the Free Software Foundation; either version 2
///	of the License, or (at your option) any later version.
///
///	This program is distributed in the hope that it will be useful,
///	but WITHOUT ANY WARRANTY; without even the implied warranty of
///	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
///	GNU General Public License for more details.
///
///	You should have received a copy of the GNU General Public License
///	along with this program; if not, write to the Free Software
///	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

#ifndef SYNTHESE_InterSYNTHESEPackageGetContentService_H__
#define SYNTHESE_InterSYNTHESEPackageGetContentService_H__

#include "FactorableTemplate.h"
#include "Function.h"

namespace synthese
{
	namespace security
	{
		class User;
	}

	namespace inter_synthese
	{
		class InterSYNTHESEPackage;

		//////////////////////////////////////////////////////////////////////////
		///	19.15 Function : InterSYNTHESEPackageGetContentService.
		/// See https://extranet.rcsmobility.com/projects/synthese/wiki/Inter_SYNTHESE_Package_get_content
		//////////////////////////////////////////////////////////////////////////
		///	@ingroup m19Functions refFunctions
		///	@author hromain
		///	@date 2013
		/// @since 3.9.0
		class InterSYNTHESEPackageGetContentService:
			public util::FactorableTemplate<server::Function,InterSYNTHESEPackageGetContentService>
		{
		public:
			static const std::string PARAMETER_SMART_URL;
			static const std::string PARAMETER_USER;
			static const std::string PARAMETER_PASSWORD;
			static const std::string PARAMETER_LOCK;
			static const std::string PARAMETER_LOCK_SERVER_NAME;
			
		protected:
			//! \name Page parameters
			//@{
				std::string _smartURL;
				std::string _userLogin;
				std::string _password;
				bool _lock;
				std::string _lockServerName;
				boost::shared_ptr<security::User> _user;
				InterSYNTHESEPackage* _package;
			//@}
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Conversion from attributes to generic parameter maps.
			/// See https://extranet.rcsmobility.com/projects/synthese/wiki/Inter_SYNTHESE_Package_get_content#Request
			//////////////////////////////////////////////////////////////////////////
			///	@return Generated parameters map
			/// @author hromain
			/// @date 2013
			/// @since 3.9.0
			util::ParametersMap _getParametersMap() const;
			
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Conversion from generic parameters map to attributes.
			/// See https://extranet.rcsmobility.com/projects/synthese/wiki/Inter_SYNTHESE_Package_get_content#Request
			//////////////////////////////////////////////////////////////////////////
			///	@param map Parameters map to interpret
			/// @author hromain
			/// @date 2013
			/// @since 3.9.0
			virtual void _setFromParametersMap(
				const util::ParametersMap& map
			);
			
			
		public:
			InterSYNTHESEPackageGetContentService();

			//! @name Setters
			//@{
				void setSmartURL(const std::string& value) { _smartURL = value; }
				void setUser(const std::string& value){ _userLogin = value; }
				void setPassword(const std::string& value){ _password = value; }
				void setLock(bool value){ _lock = value; }
				void setLockServerName(const std::string& value){ _lockServerName = value; }
			//@}



			//////////////////////////////////////////////////////////////////////////
			/// Display of the content generated by the function.
			/// @param stream Stream to display the content on.
			/// @param request the current request
			/// @author hromain
			/// @date 2013
			virtual util::ParametersMap run(std::ostream& stream, const server::Request& request) const;
			
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Gets if the function can be run according to the user of the session.
			/// @param session the current session
			/// @return true if the function can be run
			/// @author hromain
			/// @date 2013
			virtual bool isAuthorized(const server::Session* session) const;



			//////////////////////////////////////////////////////////////////////////
			/// Gets the Mime type of the content generated by the function.
			/// @return the Mime type of the content generated by the function
			/// @author hromain
			/// @date 2013
			virtual std::string getOutputMimeType() const;
		};
}	}

#endif // SYNTHESE_InterSYNTHESEPackageGetContentService_H__

