Import ('s3env')

CppSynthese3LibProject(
	s3env,
	's3-graph',
	s3env['S3VERSION'],
	source_files = s3env.Glob ('*.cpp'),
	dependencies = [
		's3-util.cpplib',
		's3-time.cpplib',
		's3-calendar.cpplib',
		's3-geometry.cpplib'
	]
)
