
//////////////////////////////////////////////////////////////////////////////////////////
///	TablesViewService class header.
///	@file TablesViewService.hpp
///	@author User
///	@date 2012
///
///	This file belongs to the SYNTHESE project (public transportation specialized software)
///	Copyright (C) 2002 Hugues Romain - RCSmobility <contact@rcsmobility.com>
///
///	This program is free software; you can redistribute it and/or
///	modify it under the terms of the GNU General Public License
///	as published by the Free Software Foundation; either version 2
///	of the License, or (at your option) any later version.
///
///	This program is distributed in the hope that it will be useful,
///	but WITHOUT ANY WARRANTY; without even the implied warranty of
///	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
///	GNU General Public License for more details.
///
///	You should have received a copy of the GNU General Public License
///	along with this program; if not, write to the Free Software
///	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

#ifndef SYNTHESE_TablesViewService_H__
#define SYNTHESE_TablesViewService_H__

#include "FactorableTemplate.h"
#include "Function.h"

namespace synthese
{
	namespace db
	{
		//////////////////////////////////////////////////////////////////////////
		///	10.15 Function : TablesViewService.
		/// See https://extranet.rcsmobility.com/projects/synthese/wiki/Tables_list
		//////////////////////////////////////////////////////////////////////////
		///	@ingroup m10Functions refFunctions
		///	@author User
		///	@date 2012
		/// @since 3.5.0
		class TablesViewService:
			public util::FactorableTemplate<server::Function,TablesViewService>
		{
		public:
			static const std::string TAG_TABLE;
			static const std::string ATTR_ID;
			static const std::string ATTR_NAME;
			static const std::string ATTR_EXPORT_ON_FILE;
			static const std::string ATTR_IS_GEOMETRY;
			static const std::string ATTR_TYPE;
			static const std::string TAG_FIELD;
			
		protected:
			//! \name Page parameters
			//@{
				/// @todo Parsed parameters declaration
				// eg : const void*	_object;
				// eg : ParametersMap			_parameters;
			//@}
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Conversion from attributes to generic parameter maps.
			/// See https://extranet.rcsmobility.com/projects/synthese/wiki/Tables_list#Request
			//////////////////////////////////////////////////////////////////////////
			///	@return Generated parameters map
			/// @author User
			/// @date 2012
			/// @since 3.5.0
			util::ParametersMap _getParametersMap() const;
			
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Conversion from generic parameters map to attributes.
			/// See https://extranet.rcsmobility.com/projects/synthese/wiki/Tables_list#Request
			//////////////////////////////////////////////////////////////////////////
			///	@param map Parameters map to interpret
			/// @author User
			/// @date 2012
			/// @since 3.5.0
			virtual void _setFromParametersMap(
				const util::ParametersMap& map
			);
			
			
		public:
			//! @name Setters
			//@{
			//	void setObject(boost::shared_ptr<const Object> value) { _object = value; }
			//@}



			//////////////////////////////////////////////////////////////////////////
			/// Display of the content generated by the function.
			/// @param stream Stream to display the content on.
			/// @param request the current request
			/// @author User
			/// @date 2012
			virtual util::ParametersMap run(std::ostream& stream, const server::Request& request) const;
			
			
			
			//////////////////////////////////////////////////////////////////////////
			/// Gets if the function can be run according to the user of the session.
			/// @param session the current session
			/// @return true if the function can be run
			/// @author User
			/// @date 2012
			virtual bool isAuthorized(const server::Session* session) const;



			//////////////////////////////////////////////////////////////////////////
			/// Gets the Mime type of the content generated by the function.
			/// @return the Mime type of the content generated by the function
			/// @author User
			/// @date 2012
			virtual std::string getOutputMimeType() const;
		};
}	}

#endif // SYNTHESE_TablesViewService_H__
