Import ('s3env')

CppSynthese3LibProject(
	s3env, 's3-cms', s3env['S3VERSION'],
	source_files = s3env.Glob ('*.cpp'),
	dependencies = ['s3-security.cpplib', 's3-server.cpplib', 's3-tree.cpplib', 's3-pt-website']
)
